import NewInvestorFormModel from './NewInvestorFormModel';
const {
  formField: {
    investor_logo,
    investor_name,
    investor_type,
    investor_date_of_incorporation,
    investor_address_city,
    investor_address_street,
    investor_address_number,
    investor_address_postalcode,
    investor_country,
    investor_industry,
    investor_registration_cert_attachment,
    director_name,
    director_email,
    director_phone_number, 
    director_id_attachment, 
    director_id_number, 
    director_id_type, 
    director_nationality,
    director_poa_attachment, 
    director_country_of_residence,
    ubo_name,
    ubo_email,
    ubo_phone_number, 
    ubo_id_attachment, 
    ubo_id_number, 
    ubo_id_type, 
    ubo_nationality,
    ubo_poa_attachment, 
    ubo_country_of_residence,
    ebit,
    balance_sheet_attachment,
    income_statement_attachment,
    net_profit,
    financials_rating,
    financials_reporting_period,
    sales,
    total_assets,
    retained_earnings,
    working_capital,
    bank_account_number,
    bank_account_sortcode,
    bank_country,
    bank_name,
    bank_routing_number,
    bic_swift_code,
    iban,
  }
} = NewInvestorFormModel;

export default { 
  [investor_logo.name]: '',
  [investor_name.name]: '',
  [investor_type.name]: '',
  [investor_date_of_incorporation.name]: '',
  [investor_address_city.name]: '',
  [investor_address_street.name]: '',
  [investor_address_number.name]: '',
  [investor_address_postalcode.name]: '',
  [investor_country.name]: undefined,
  [investor_industry.name]: undefined,
  [investor_registration_cert_attachment.name]: '',
  [director_name.name]: '',
  [director_email.name]: '',
  [director_phone_number.name]: '',
  [director_id_attachment.name]: '',
  [director_id_number.name]: '',
  [director_id_type.name]: '',
  [director_nationality.name]: undefined,
  [director_poa_attachment.name]: '',
  [director_country_of_residence.name]: undefined,
  [ubo_name.name]: '',
  [ubo_email.name]: '',
  [ubo_phone_number.name]: '',
  [ubo_id_attachment.name]: '',
  [ubo_id_number.name]: '',
  [ubo_id_type.name]: '',
  [ubo_nationality.name]: undefined,
  [ubo_poa_attachment.name]: '',
  [ubo_country_of_residence.name]: undefined,
  [ebit.name]: '',
  [balance_sheet_attachment.name]: '',
  [income_statement_attachment.name]: '',
  [net_profit.name]: '',
  [financials_rating.name]: '',
  [financials_reporting_period.name]: '',
  [sales.name]: '',
  [total_assets.name]: '',
  [retained_earnings.name]: '',
  [working_capital.name]: '',
  [bank_account_number.name]: '',
  [bank_account_sortcode.name]: '',
  [bank_country.name]: undefined,
  [bank_name.name]: '',
  [bank_routing_number.name]: '',
  [bic_swift_code.name]: '',
  [iban.name]: '',
};
