projects:
  client:
    schemaPath: src/graphql/schema.json
    includes:
      - >-
        /Users/tobiaspfuetze/Documents/VSCode/Originate/Frontend/Client/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
