import NewSupplierFormModel from './NewSupplierFormModel';
const {
  formField: {
    supplier_logo,
    supplier_name,
    supplier_type,
    supplier_date_of_incorporation,
    supplier_address_city,
    supplier_address_street,
    supplier_address_postalcode,
    supplier_country,
    supplier_industry,
    supplier_registration_cert_attachment,
    supplier_articles_of_association_attachment,
    supplier_shareholder_list_attachment,
    supplier_director_list_attachment,
    supplier_register_number,
    supplier_trading_name,
    supplier_website,
    supplier_address_refinment,
    supplier_industry_code,
    director_name,
    director_email,
    director_phone_number, 
    director_id_attachment, 
    director_id_number, 
    director_id_type, 
    director_nationality,
    director_poa_attachment, 
    director_country_of_residence,
    ubo_name,
    ubo_email,
    ubo_phone_number, 
    ubo_id_attachment, 
    ubo_id_number, 
    ubo_id_type, 
    ubo_nationality,
    ubo_poa_attachment, 
    ubo_country_of_residence,
    buyerId,
    accounts_payable,
    accounts_receivable,
    cash,
    equity_book_value,
    equity_market_value,
    interest_expenses,
    inventory,
    retained_earnings,
    short_term_debt,
    working_capital,
    ebit,
    financials_attachment,
    net_profit,
    financials_rating,
    financials_reporting_period,
    sales,
    total_assets,
    total_liabilities
  }
} = NewSupplierFormModel;

export default { 
  [supplier_logo.name]: '',
  [supplier_name.name]: '',
  [supplier_trading_name.name]: '',
  [supplier_website.name]: '',
  [supplier_type.name]: '',
  [supplier_date_of_incorporation.name]: '',
  [supplier_address_city.name]: '',
  [supplier_address_street.name]: '',
  [supplier_address_postalcode.name]: '',
  [supplier_address_refinment.name]: '',
  [supplier_country.name]: undefined,
  [supplier_industry.name]: undefined,
  [supplier_industry_code.name]: undefined,
  [supplier_register_number.name]: '',
  [supplier_registration_cert_attachment.name]: '',
  [supplier_articles_of_association_attachment.name]: '',
  [supplier_shareholder_list_attachment.name]: '',
  [supplier_director_list_attachment.name]: '',
  [director_name.name]: '',
  [director_email.name]: '',
  [director_phone_number.name]: '',
  [director_id_attachment.name]: '',
  [director_id_number.name]: '',
  [director_id_type.name]: '',
  [director_nationality.name]: undefined,
  [director_poa_attachment.name]: '',
  [director_country_of_residence.name]: undefined,
  [ubo_name.name]: '',
  [ubo_email.name]: '',
  [ubo_phone_number.name]: '',
  [ubo_id_attachment.name]: '',
  [ubo_id_number.name]: '',
  [ubo_id_type.name]: '',
  [ubo_nationality.name]: undefined,
  [ubo_poa_attachment.name]: '',
  [ubo_country_of_residence.name]: undefined,
  [ebit.name]: '',
  [financials_attachment.name]: '',
  [buyerId.name]: '',
  [net_profit.name]: '',
  [financials_rating.name]: '',
  [financials_reporting_period.name]: '',
  [sales.name]: '',
  [total_assets.name]: '',
  [total_liabilities.name]: '',
  [accounts_payable.name]: '',
  [accounts_receivable.name]: '',
  [cash.name]: '',
  [equity_book_value.name]: '',
  [equity_market_value.name]: '',
  [interest_expenses.name]: '',
  [inventory.name]: '',
  [retained_earnings.name]: '',
  [short_term_debt.name]: '',
  [working_capital.name]: '',
};
