import NewFinancialsFormModel from './NewFinancialsFormModel';
const {
  formField: {
    supplierId,
    buyerId,
    identityId,
    financials_attachment,
    balance_sheet_attachment,
    income_statement_attachment,
    marketable_securities,
    accounts_receivable,
    inventory,
    goodwill,
    other_current_assets,
    other_non_current_assets,
    accumulated_depreciation,
    total_assets,
    short_term_debt,
    accounts_payable,
    accured_expenses,
    unearned_revenue,
    long_term_debt,
    other_current_liabilities,
    other_long_term_liabilities,
    income_tax_payable,
    dividends_payable,
    total_liabilities,
    common_stock,
    preferred_stock,
    paid_in_capital,
    retained_earnings,
    total_equity,
    equity_book_value,
    equity_market_value,
    sales,
    cost_of_goods_sold,
    operating_expenses,
    marketing_expenses,
    bad_debt_expenses,
    ebit,
    interest_expenses,
    depreciation_expenses,
    sale_purchase_of_fixed_asset,
    extraordinary_income,
    tax_expenses,
    net_profit,
    financials_rating,
    financials_reporting_period,
    cash,
    working_capital,
  }
} = NewFinancialsFormModel;

export default {
  [supplierId.name]: '',
  [buyerId.name]: '',
  [identityId.name]: '',
  [financials_attachment.name]: '',
  [balance_sheet_attachment.name]: '',
  [income_statement_attachment.name]: '',
  [marketable_securities.name]: '',
  [accounts_receivable.name]: '',
  [inventory.name]: '',
  [goodwill.name]: '',
  [other_current_assets.name]: '',
  [other_non_current_assets.name]: '',
  [accumulated_depreciation.name]: '',
  [total_assets.name]: '',
  [short_term_debt.name]: '',
  [accounts_payable.name]: '',
  [accured_expenses.name]: '',
  [unearned_revenue.name]: '',
  [long_term_debt.name]: '',
  [other_current_liabilities.name]: '',
  [other_long_term_liabilities.name]: '',
  [income_tax_payable.name]: '',
  [dividends_payable.name]: '',
  [total_liabilities.name]: '',
  [common_stock.name]: '',
  [preferred_stock.name]: '',
  [paid_in_capital.name]: '',
  [retained_earnings.name]: '',
  [total_equity.name]: '',
  [equity_book_value.name]: '',
  [equity_market_value.name]: '',
  [sales.name]: '',
  [cost_of_goods_sold.name]: '',
  [operating_expenses.name]: '',
  [marketing_expenses.name]: '',
  [bad_debt_expenses.name]: '',
  [ebit.name]: '',
  [interest_expenses.name]: '',
  [depreciation_expenses.name]: '',
  [sale_purchase_of_fixed_asset.name]: '',
  [extraordinary_income.name]: '',
  [tax_expenses.name]: '',
  [net_profit.name]: '',
  [financials_rating.name]: '',
  [financials_reporting_period.name]: '',
  [cash.name]: '',
  [working_capital.name]: '',
};
