import NewFinancialsFormModel from "./NewFinancialsFormModel";
const {
  formField: {
    supplierId,
    buyerId,
    identityId,
    financials_attachment,
    balance_sheet_attachment,
    financials_reporting_period,
    cash,
    accounts_receivable,
    inventory,
    other_current_assets,
    sale_purchase_of_fixed_asset,
    goodwill,
    other_non_current_assets,
    total_assets,
    accounts_payable,
    current_long_term_debt,
    other_current_liabilities,
    current_liabilities,
    long_term_debt,
    other_long_term_liabilities,
    total_liabilities,
    total_equity,
    total_liabilities_and_equity,
    income_statement_attachment,
    sales,
    cost_of_goods_sold,
    depreciation_expenses,
    operating_expenses,
    interest_expenses,
    other_expenses,
    income_tax_expense,
    extraordinary_income,
    cash_flow_from_operating_activities,
    inventory_turnover
  },
} = NewFinancialsFormModel;

const values = {
  [supplierId.name]: "",
  [buyerId.name]: "",
  [identityId.name]: "",
  [financials_attachment.name]: "",
  [balance_sheet_attachment.name]: "",
  [income_statement_attachment.name]: "",
  [financials_reporting_period.name]: "",
  [cash.name]: "",
  [accounts_receivable.name]: "",
  [inventory.name]: "",
  [other_current_assets.name]: "",
  [sale_purchase_of_fixed_asset.name]: "",
  [goodwill.name]: "",
  [other_non_current_assets.name]: "",
  [total_assets.name]: "",
  [accounts_payable.name]: "",
  [current_long_term_debt.name]: "",
  [other_current_liabilities.name]: "",
  [current_liabilities.name]: "",
  [long_term_debt.name]: "",
  [other_long_term_liabilities.name]: "",
  [total_liabilities.name]: "",
  [total_equity.name]: "",
  [total_liabilities_and_equity.name]: "",
  [sales.name]: "",
  [cost_of_goods_sold.name]: "",
  [depreciation_expenses.name]: "",
  [operating_expenses.name]: "",
  [interest_expenses.name]: "",
  [other_expenses.name]: "",
  [extraordinary_income.name]: "",
  [income_tax_expense.name]: "",
  [cash_flow_from_operating_activities.name]: "",
  [inventory_turnover.name]: "",
};

export default values;
