import NewBuyerFormModel from "./NewBuyerFormModel";
const {
  formField: {
    buyer_name,
    buyer_address_city,
    buyer_address_postalcode,
    buyer_address_street,
    buyer_country,
    buyer_website,
    buyer_contact_name,
    buyer_contact_email,
    buyer_currency,
    buyer_insurance_name,
    buyer_loan_request_amount,
    buyer_next_year_projected_transaction_amount,
    buyer_payment_terms,
    buyer_previous_year_transaction_amount,
    buyer_reporting_year_transaction_amount,
    buyer_previous_year_number_invoices,
    buyer_sample_trading_docs_attachment,
    buyer_sold_goods_description,
    balance_sheet_attachment,
    income_statement_attachment,
    financials_reporting_period,
    sales,
    net_profit,
    ebit,
    current_assets,
    current_liabilities,
    cost_of_goods_sold,
    total_equity,
    buyer_supplier_year_business_relation_started,
    buyer_existing_disputes,
    buyer_finance_department_contact_email,
    buyer_invoices_paid_on_time,
    buyer_invoices_past_due_30_days,
    buyer_invoices_past_due_60_days,
    buyer_invoices_past_due_90_days,
    buyer_use_of_goods_purchased
  },
} = NewBuyerFormModel;

const values = {
  [buyer_address_city.name]: "",
  [buyer_address_street.name]: "",
  [buyer_address_postalcode.name]: "",
  [buyer_country.name]: undefined,
  [buyer_website.name]: "",
  [buyer_contact_name.name]: "",
  [buyer_contact_email.name]: "",
  [buyer_name.name]: "",
  [buyer_currency.name]: undefined,
  [buyer_insurance_name.name]: "",
  [buyer_loan_request_amount.name]: "",
  [buyer_next_year_projected_transaction_amount.name]: "",
  [buyer_payment_terms.name]: "",
  [buyer_previous_year_transaction_amount.name]: "",
  [buyer_reporting_year_transaction_amount.name]: "",
  [buyer_previous_year_number_invoices.name]: "",
  [buyer_sample_trading_docs_attachment.name]: "",
  [buyer_sold_goods_description.name]: "",
  [buyer_supplier_year_business_relation_started.name]: "",
  [buyer_existing_disputes.name]: "",
  [buyer_finance_department_contact_email.name]: "",
  [buyer_invoices_paid_on_time.name]: "",
  [buyer_invoices_past_due_30_days.name]: "",
  [buyer_invoices_past_due_60_days.name]: "",
  [buyer_invoices_past_due_90_days.name]: "",
  [buyer_use_of_goods_purchased.name]: "",
  [balance_sheet_attachment.name]: "",
  [income_statement_attachment.name]: "",
  [net_profit.name]: "",
  [ebit.name]: "",
  [current_assets.name]: "",
  [current_liabilities.name]: "",
  [cost_of_goods_sold.name]: "",
  [financials_reporting_period.name]: "",
  [sales.name]: "",
  [total_equity.name]: "",
};

export default values;
