const countries = [
  { label: "Afghanistan", ISO3: "AFG", code: "004" },
  { label: "Albania", ISO3: "ALB", code: "008" },
  { label: "Algeria", ISO3: "DZA", code: "012" },
  { label: "Andorra", ISO3: "AND", code: "020" },
  { label: "Angola", ISO3: "AGO", code: "024" },
  { label: "Antigua and Barbuda", ISO3: "ATG", code: "028" },
  { label: "Argentina", ISO3: "ARG", code: "032" },
  { label: "Armenia", ISO3: "ARM", code: "051" },
  { label: "Australia", ISO3: "AUS", code: "036" },
  { label: "Austria", ISO3: "AUT", code: "040" },
  { label: "Azerbaijan", ISO3: "AZE", code: "031" },
  { label: "Bahamas", ISO3: "BHS", code: "044" },
  { label: "Bahrain", ISO3: "BHR", code: "048" },
  { label: "Bangladesh", ISO3: "BGD", code: "050" },
  { label: "Barbados", ISO3: "BRB", code: "052" },
  { label: "Belarus", ISO3: "BLR", code: "112" },
  { label: "Belgium", ISO3: "BEL", code: "056" },
  { label: "Belize", ISO3: "BLZ", code: "084" },
  { label: "Benin", ISO3: "BEN", code: "204" },
  { label: "Bhutan", ISO3: "BTN", code: "064" },
  { label: "Bolivia (Plurinational State of)", ISO3: "BOL", code: "068" },
  { label: "Bosnia and Herzegovina", ISO3: "BIH", code: "070" },
  { label: "Botswana", ISO3: "BWA", code: "072" },
  { label: "Brazil", ISO3: "BRA", code: "076" },
  { label: "Brunei Darussalam", ISO3: "BRN", code: "096" },
  { label: "Bulgaria", ISO3: "BGR", code: "100" },
  { label: "Burkina Faso", ISO3: "BFA", code: "854" },
  { label: "Burundi", ISO3: "BDI", code: "108" },
  { label: "Cabo Verde", ISO3: "CPV", code: "132" },
  { label: "Cambodia", ISO3: "KHM", code: "116" },
  { label: "Cameroon", ISO3: "CMR", code: "120" },
  { label: "Canada", ISO3: "CAN", code: "124" },
  { label: "Cayman Islands", ISO3: "CYM", code: "136" },
  { label: "Central African Republic", ISO3: "CAF", code: "140" },
  { label: "Chad", ISO3: "TCD", code: "148" },
  { label: "Chile", ISO3: "CHL", code: "152" },
  { label: "China", ISO3: "CHN", code: "156" },
  { label: "Christmas Island", ISO3: "CXR", code: "162" },
  { label: "Cocos (Keeling) Islands", ISO3: "CCK", code: "166" },
  { label: "Colombia", ISO3: "COL", code: "170" },
  { label: "Comoros", ISO3: "COM", code: "174" },
  { label: "Congo", ISO3: "COG", code: "178" },
  {
    label: "Congo, Democratic Republic of the",
    ISO3: "COD",
    code: "180",
  },
  { label: "Cook Islands", ISO3: "COK", code: "184" },
  { label: "Costa Rica", ISO3: "CRI", code: "188" },
  { label: "Côte d'Ivoire", ISO3: "CIV", code: "384" },
  { label: "Croatia", ISO3: "HRV", code: "191" },
  { label: "Cuba", ISO3: "CUB", code: "192" },
  { label: "Curaçao", ISO3: "CUW", code: "531" },
  { label: "Cyprus", ISO3: "CYP", code: "196" },
  { label: "Czechia", ISO3: "CZE", code: "203" },
  { label: "Denmark", ISO3: "DNK", code: "208" },
  { label: "Djibouti", ISO3: "DJI", code: "262" },
  { label: "Dominica", ISO3: "DMA", code: "212" },
  { label: "Dominican Republic", ISO3: "DOM", code: "214" },
  { label: "Ecuador", ISO3: "ECU", code: "218" },
  { label: "Egypt", ISO3: "EGY", code: "818" },
  { label: "El Salvador", ISO3: "SLV", code: "222" },
  { label: "Equatorial Guinea", ISO3: "GNQ", code: "226" },
  { label: "Eritrea", ISO3: "ERI", code: "232" },
  { label: "Estonia", ISO3: "EST", code: "233" },
  { label: "Eswatini", ISO3: "SWZ", code: "748" },
  { label: "Ethiopia", ISO3: "ETH", code: "231" },
  {
    label: "Falkland Islands (Malvinas)",
    ISO3: "FLK",
    code: "238",
  },
  { label: "Faroe Islands", ISO3: "FRO", code: "234" },
  { label: "Fiji", ISO3: "FJI", code: "242" },
  { label: "Finland", ISO3: "FIN", code: "246" },
  { label: "France", ISO3: "FRA", code: "250" },
  { label: "French Guiana", ISO3: "GUF", code: "254" },
  { label: "French Polynesia", ISO3: "PYF", code: "258" },
  { label: "Gabon", ISO3: "GAB", code: "266" },
  { label: "Gambia", ISO3: "GMB", code: "270" },
  { label: "Georgia", ISO3: "GEO", code: "268" },
  { label: "Germany", ISO3: "DEU", code: "276" },
  { label: "Ghana", ISO3: "GHA", code: "288" },
  { label: "Gibraltar", ISO3: "GIB", code: "292" },
  { label: "Greece", ISO3: "GRC", code: "300" },
  { label: "Greenland", ISO3: "GRL", code: "304" },
  { label: "Grenada", ISO3: "GRD", code: "308" },
  { label: "Guadeloupe", ISO3: "GLP", code: "312" },
  { label: "Guam", ISO3: "GUM", code: "316" },
  { label: "Guatemala", ISO3: "GTM", code: "320" },
  { label: "Guernsey", ISO3: "GGY", code: "831" },
  { label: "Guinea", ISO3: "GIN", code: "324" },
  { label: "Guinea-Bissau", ISO3: "GNB", code: "624" },
  { label: "Guyana", ISO3: "GUY", code: "328" },
  { label: "Haiti", ISO3: "HTI", code: "332" },
  { label: "Holy See", ISO3: "VAT", code: "336" },
  { label: "Honduras", ISO3: "HND", code: "340" },
  { label: "Hong Kong (SAR)", ISO3: "HKG", code: "344" },
  { label: "Hungary", ISO3: "HUN", code: "348" },
  { label: "Iceland", ISO3: "ISL", code: "352" },
  { label: "India", ISO3: "IND", code: "356" },
  { label: "Indonesia", ISO3: "IDN", code: "360" },
  {
    label: "Iran (Islamic Republic of)",
    ISO3: "IRN",
    code: "364",
  },
  { label: "Iraq", ISO3: "IRQ", code: "368" },
  { label: "Ireland", ISO3: "IRL", code: "372" },
  { label: "Isle of Man", ISO3: "IMN", code: "833" },
  { label: "Israel", ISO3: "ISR", code: "376" },
  { label: "Italy", ISO3: "ITA", code: "380" },
  { label: "Jamaica", ISO3: "JAM", code: "388" },
  { label: "Japan", ISO3: "JPN", code: "392" },
  { label: "Jersey", ISO3: "JEY", code: "832" },
  { label: "Jordan", ISO3: "JOR", code: "400" },
  { label: "Kazakhstan", ISO3: "KAZ", code: "398" },
  { label: "Kenya", ISO3: "KEN", code: "404" },
  { label: "Kiribati", ISO3: "KIR", code: "296" },
  {
    label: "North Korea (Democratic People's Republic of)",
    ISO3: "PRK",
    code: "408",
  },
  { label: "South Korea", ISO3: "KOR", code: "410" },
  { label: "Kuwait", ISO3: "KWT", code: "414" },
  { label: "Kyrgyzstan", ISO3: "KGZ", code: "417" },
  {
    label: "Lao People's Democratic Republic",
    ISO3: "LAO",
    code: "418",
  },
  { label: "Latvia", ISO3: "LVA", code: "428" },
  { label: "Lebanon", ISO3: "LBN", code: "422" },
  { label: "Lesotho", ISO3: "LSO", code: "426" },
  { label: "Liberia", ISO3: "LBR", code: "430" },
  { label: "Libya", ISO3: "LBY", code: "434" },
  { label: "Liechtenstein", ISO3: "LIE", code: "438" },
  { label: "Lithuania", ISO3: "LTU", code: "440" },
  { label: "Luxembourg", ISO3: "LUX", code: "442" },
  { label: "Macao", ISO3: "MAC", code: "446" },
  { label: "Madagascar", ISO3: "MDG", code: "450" },
  { label: "Malawi", ISO3: "MWI", code: "454" },
  { label: "Malaysia", ISO3: "MYS", code: "458" },
  { label: "Maldives", ISO3: "MDV", code: "462" },
  { label: "Mali", ISO3: "MLI", code: "466" },
  { label: "Malta", ISO3: "MLT", code: "470" },
  { label: "Marshall Islands", ISO3: "MHL", code: "584" },
  { label: "Martinique", ISO3: "MTQ", code: "474" },
  { label: "Mauritania", ISO3: "MRT", code: "478" },
  { label: "Mauritius", ISO3: "MUS", code: "480" },
  { label: "Mayotte", ISO3: "MYT", code: "175" },
  { label: "Mexico", ISO3: "MEX", code: "484" },
  {
    label: "Micronesia (Federated States of)",
    ISO3: "FSM",
    code: "583",
  },
  { label: "Moldova, Republic of", ISO3: "MDA", code: "498" },
  { label: "Monaco", ISO3: "MCO", code: "492" },
  { label: "Mongolia", ISO3: "MNG", code: "496" },
  { label: "Montenegro", ISO3: "MNE", code: "499" },
  { label: "Montserrat", ISO3: "MSR", code: "500" },
  { label: "Morocco", ISO3: "MAR", code: "504" },
  { label: "Mozambique", ISO3: "MOZ", code: "508" },
  { label: "Myanmar", ISO3: "MMR", code: "104" },
  { label: "Namibia", ISO3: "NAM", code: "516" },
  { label: "Nauru", ISO3: "NRU", code: "520" },
  { label: "Nepal", ISO3: "NPL", code: "524" },
  { label: "Netherlands", ISO3: "NLD", code: "528" },
  { label: "New Caledonia", ISO3: "NCL", code: "540" },
  { label: "New Zealand", ISO3: "NZL", code: "554" },
  { label: "Nicaragua", ISO3: "NIC", code: "558" },
  { label: "Niger", ISO3: "NER", code: "562" },
  { label: "Nigeria", ISO3: "NGA", code: "566" },
  { label: "Niue", ISO3: "NIU", code: "570" },
  { label: "Norfolk Island", ISO3: "NFK", code: "574" },
  { label: "North Macedonia", ISO3: "MKD", code: "807" },
  { label: "Northern Mariana Islands", ISO3: "MNP", code: "580" },
  { label: "Norway", ISO3: "NOR", code: "578" },
  { label: "Oman", ISO3: "OMN", code: "512" },
  { label: "Pakistan", ISO3: "PAK", code: "586" },
  { label: "Palau", ISO3: "PLW", code: "585" },
  { label: "Palestine, State of", ISO3: "PSE", code: "275" },
  { label: "Panama", ISO3: "PAN", code: "591" },
  { label: "Papua New Guinea", ISO3: "PNG", code: "598" },
  { label: "Paraguay", ISO3: "PRY", code: "600" },
  { label: "Peru", ISO3: "PER", code: "604" },
  { label: "Philippines", ISO3: "PHL", code: "608" },
  { label: "Pitcairn", ISO3: "PCN", code: "612" },
  { label: "Poland", ISO3: "POL", code: "616" },
  { label: "Portugal", ISO3: "PRT", code: "620" },
  { label: "Puerto Rico", ISO3: "PRI", code: "630" },
  { label: "Qatar", ISO3: "QAT", code: "634" },
  { label: "Réunion", ISO3: "REU", code: "638" },
  { label: "Romania", ISO3: "ROU", code: "642" },
  { label: "Russian Federation", ISO3: "RUS", code: "643" },
  { label: "Rwanda", ISO3: "RWA", code: "646" },
  { label: "Saint Barthélemy", ISO3: "BLM", code: "652" },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    ISO3: "SHN",
    code: "654",
  },
  { label: "Saint Kitts and Nevis", ISO3: "KNA", code: "659" },
  { label: "Saint Lucia", ISO3: "LCA", code: "662" },
  {
    label: "Saint Martin (French part)",
    ISO3: "MAF",
    code: "663",
  },
  {
    label: "Saint Pierre and Miquelon",
    ISO3: "SPM",
    code: "666",
  },
  {
    label: "Saint Vincent and the Grenadines",
    ISO3: "VCT",
    code: "670",
  },
  { label: "Samoa", ISO3: "WSM", code: "882" },
  { label: "San Marino", ISO3: "SMR", code: "674" },
  { label: "Sao Tome and Principe", ISO3: "STP", code: "678" },
  { label: "Saudi Arabia", ISO3: "SAU", code: "682" },
  { label: "Senegal", ISO3: "SEN", code: "686" },
  { label: "Serbia", ISO3: "SRB", code: "688" },
  { label: "Seychelles", ISO3: "SYC", code: "690" },
  { label: "Sierra Leone", ISO3: "SLE", code: "694" },
  { label: "Singapore", ISO3: "SGP", code: "702" },
  {
    label: "Sint Maarten (Dutch part)",
    ISO3: "SXM",
    code: "534",
  },
  { label: "Slovakia", ISO3: "SVK", code: "703" },
  { label: "Slovenia", ISO3: "SVN", code: "705" },
  { label: "Solomon Islands", ISO3: "SLB", code: "090" },
  { label: "Somalia", ISO3: "SOM", code: "706" },
  { label: "South Africa", ISO3: "ZAF", code: "710" },
  {
    label: "South Georgia and the South Sandwich Islands",
    ISO3: "SGS",
    code: "239",
  },
  { label: "South Sudan", ISO3: "SSD", code: "728" },
  { label: "Spain", ISO3: "ESP", code: "724" },
  { label: "Sri Lanka", ISO3: "LKA", code: "144" },
  { label: "Sudan", ISO3: "SDN", code: "729" },
  { label: "Surilabel", ISO3: "SUR", code: "740" },
  { label: "Svalbard and Jan Mayen", ISO3: "SJM", code: "744" },
  { label: "Sweden", ISO3: "SWE", code: "752" },
  { label: "Switzerland", ISO3: "CHE", code: "756" },
  { label: "Syrian Arab Republic", ISO3: "SYR", code: "760" },
  {
    label: "Taiwan",
    ISO3: "TWN",
    code: "158",
  },
  { label: "Tajikistan", ISO3: "TJK", code: "762" },
  {
    label: "Tanzania, United Republic of",
    ISO3: "TZA",
    code: "834",
  },
  { label: "Thailand", ISO3: "THA", code: "764" },
  { label: "Timor-Leste", ISO3: "TLS", code: "626" },
  { label: "Togo", ISO3: "TGO", code: "768" },
  { label: "Tokelau", ISO3: "TKL", code: "772" },
  { label: "Tonga", ISO3: "TON", code: "776" },
  { label: "Trinidad and Tobago", ISO3: "TTO", code: "780" },
  { label: "Tunisia", ISO3: "TUN", code: "788" },
  { label: "Turkey", ISO3: "TUR", code: "792" },
  { label: "Turkmenistan", ISO3: "TKM", code: "795" },
  { label: "Turks and Caicos Islands", ISO3: "TCA", code: "796" },
  { label: "Tuvalu", ISO3: "TUV", code: "798" },
  { label: "Uganda", ISO3: "UGA", code: "800" },
  { label: "Ukraine", ISO3: "UKR", code: "804" },
  { label: "United Arab Emirates", ISO3: "ARE", code: "784" },
  {
    label: "United Kingdom",
    ISO3: "GBR",
    code: "826",
  },
  { label: "United States of America", ISO3: "USA", code: "840" },
  {
    label: "United States Minor Outlying Islands",
    ISO3: "UMI",
    code: "581",
  },
  { label: "Uruguay", ISO3: "URY", code: "858" },
  { label: "Uzbekistan", ISO3: "UZB", code: "860" },
  { label: "Vanuatu", ISO3: "VUT", code: "548" },
  {
    label: "Venezuela (Bolivarian Republic of)",
    ISO3: "VEN",
    code: "862",
  },
  { label: "Vietnam", ISO3: "VNM", code: "704" },
  { label: "Virgin Islands (British)", ISO3: "VGB", code: "092" },
  { label: "Virgin Islands (U.S.)", ISO3: "VIR", code: "850" },
  { label: "Wallis and Futuna", ISO3: "WLF", code: "876" },
  { label: "Western Sahara", ISO3: "ESH", code: "732" },
  { label: "Yemen", ISO3: "YEM", code: "887" },
  { label: "Zambia", ISO3: "ZMB", code: "894" },
  { label: "Zimbabwe", ISO3: "ZWE", code: "716" },
];

export default countries;
