const countries = [
  {
    label: "Afghanistan",
    ISO2: "AF",
    ISO3: "AFG",
    code: "004",
  },
  {
    label: "Åland Islands",
    ISO2: "AX",
    ISO3: "ALA",
    code: "248",
  },
  {
    label: "Albania",
    ISO2: "AL",
    ISO3: "ALB",
    code: "008",
  },
  {
    label: "Algeria",
    ISO2: "DZ",
    ISO3: "DZA",
    code: "012",
  },
  {
    label: "American Samoa",
    ISO2: "AS",
    ISO3: "ASM",
    code: "016",
  },
  {
    label: "Andorra",
    ISO2: "AD",
    ISO3: "AND",
    code: "020",
  },
  {
    label: "Angola",
    ISO2: "AO",
    ISO3: "AGO",
    code: "024",
  },
  {
    label: "Anguilla",
    ISO2: "AI",
    ISO3: "AIA",
    code: "660",
  },
  {
    label: "Antarctica",
    ISO2: "AQ",
    ISO3: "ATA",
    code: "010",
  },
  {
    label: "Antigua and Barbuda",
    ISO2: "AG",
    ISO3: "ATG",
    code: "028",
  },
  {
    label: "Argentina",
    ISO2: "AR",
    ISO3: "ARG",
    code: "032",
  },
  {
    label: "Armenia",
    ISO2: "AM",
    ISO3: "ARM",
    code: "051",
  },
  {
    label: "Aruba",
    ISO2: "AW",
    ISO3: "ABW",
    code: "533",
  },
  {
    label: "Australia",
    ISO2: "AU",
    ISO3: "AUS",
    code: "036",
  },
  {
    label: "Austria",
    ISO2: "AT",
    ISO3: "AUT",
    code: "040",
  },
  {
    label: "Azerbaijan",
    ISO2: "AZ",
    ISO3: "AZE",
    code: "031",
  },
  {
    label: "Bahamas",
    ISO2: "BS",
    ISO3: "BHS",
    code: "044",
  },
  {
    label: "Bahrain",
    ISO2: "BH",
    ISO3: "BHR",
    code: "048",
  },
  {
    label: "Bangladesh",
    ISO2: "BD",
    ISO3: "BGD",
    code: "050",
  },
  {
    label: "Barbados",
    ISO2: "BB",
    ISO3: "BRB",
    code: "052",
  },
  {
    label: "Belarus",
    ISO2: "BY",
    ISO3: "BLR",
    code: "112",
  },
  {
    label: "Belgium",
    ISO2: "BE",
    ISO3: "BEL",
    code: "056",
  },
  {
    label: "Belize",
    ISO2: "BZ",
    ISO3: "BLZ",
    code: "084",
  },
  {
    label: "Benin",
    ISO2: "BJ",
    ISO3: "BEN",
    code: "204",
  },
  {
    label: "Bermuda",
    ISO2: "BM",
    ISO3: "BMU",
    code: "060",
  },
  {
    label: "Bhutan",
    ISO2: "BT",
    ISO3: "BTN",
    code: "064",
  },
  {
    label: "Bolivia (Plurinational State of)",
    ISO2: "BO",
    ISO3: "BOL",
    code: "068",
  },
  {
    label: "Bonaire, Sint Eustatius and Saba",
    ISO2: "BQ",
    ISO3: "BES",
    code: "535",
  },
  {
    label: "Bosnia and Herzegovina",
    ISO2: "BA",
    ISO3: "BIH",
    code: "070",
  },
  {
    label: "Botswana",
    ISO2: "BW",
    ISO3: "BWA",
    code: "072",
  },
  {
    label: "Bouvet Island",
    ISO2: "BV",
    ISO3: "BVT",
    code: "074",
  },
  {
    label: "Brazil",
    ISO2: "BR",
    ISO3: "BRA",
    code: "076",
  },
  {
    label: "British Indian Ocean Territory",
    ISO2: "IO",
    ISO3: "IOT",
    code: "086",
  },
  {
    label: "Brunei Darussalam",
    ISO2: "BN",
    ISO3: "BRN",
    code: "096",
  },
  {
    label: "Bulgaria",
    ISO2: "BG",
    ISO3: "BGR",
    code: "100",
  },
  {
    label: "Burkina Faso",
    ISO2: "BF",
    ISO3: "BFA",
    code: "854",
  },
  {
    label: "Burundi",
    ISO2: "BI",
    ISO3: "BDI",
    code: "108",
  },
  {
    label: "Cabo Verde",
    ISO2: "CV",
    ISO3: "CPV",
    code: "132",
  },
  {
    label: "Cambodia",
    ISO2: "KH",
    ISO3: "KHM",
    code: "116",
  },
  {
    label: "Cameroon",
    ISO2: "CM",
    ISO3: "CMR",
    code: "120",
  },
  {
    label: "Canada",
    ISO2: "CA",
    ISO3: "CAN",
    code: "124",
  },
  {
    label: "Cayman Islands",
    ISO2: "KY",
    ISO3: "CYM",
    code: "136",
  },
  {
    label: "Central African Republic",
    ISO2: "CF",
    ISO3: "CAF",
    code: "140",
  },
  {
    label: "Chad",
    ISO2: "TD",
    ISO3: "TCD",
    code: "148",
  },
  {
    label: "Chile",
    ISO2: "CL",
    ISO3: "CHL",
    code: "152",
  },
  {
    label: "China",
    ISO2: "CN",
    ISO3: "CHN",
    code: "156",
  },
  {
    label: "Christmas Island",
    ISO2: "CX",
    ISO3: "CXR",
    code: "162",
  },
  {
    label: "Cocos (Keeling) Islands",
    ISO2: "CC",
    ISO3: "CCK",
    code: "166",
  },
  {
    label: "Colombia",
    ISO2: "CO",
    ISO3: "COL",
    code: "170",
  },
  {
    label: "Comoros",
    ISO2: "KM",
    ISO3: "COM",
    code: "174",
  },
  {
    label: "Congo",
    ISO2: "CG",
    ISO3: "COG",
    code: "178",
  },
  {
    label: "Congo, Democratic Republic of the",
    ISO2: "CD",
    ISO3: "COD",
    code: "180",
  },
  {
    label: "Cook Islands",
    ISO2: "CK",
    ISO3: "COK",
    code: "184",
  },
  {
    label: "Costa Rica",
    ISO2: "CR",
    ISO3: "CRI",
    code: "188",
  },
  {
    label: "Côte d'Ivoire",
    ISO2: "CI",
    ISO3: "CIV",
    code: "384",
  },
  {
    label: "Croatia",
    ISO2: "HR",
    ISO3: "HRV",
    code: "191",
  },
  {
    label: "Cuba",
    ISO2: "CU",
    ISO3: "CUB",
    code: "192",
  },
  {
    label: "Curaçao",
    ISO2: "CW",
    ISO3: "CUW",
    code: "531",
  },
  {
    label: "Cyprus",
    ISO2: "CY",
    ISO3: "CYP",
    code: "196",
  },
  {
    label: "Czechia",
    ISO2: "CZ",
    ISO3: "CZE",
    code: "203",
  },
  {
    label: "Denmark",
    ISO2: "DK",
    ISO3: "DNK",
    code: "208",
  },
  {
    label: "Djibouti",
    ISO2: "DJ",
    ISO3: "DJI",
    code: "262",
  },
  {
    label: "Dominica",
    ISO2: "DM",
    ISO3: "DMA",
    code: "212",
  },
  {
    label: "Dominican Republic",
    ISO2: "DO",
    ISO3: "DOM",
    code: "214",
  },
  {
    label: "Ecuador",
    ISO2: "EC",
    ISO3: "ECU",
    code: "218",
  },
  {
    label: "Egypt",
    ISO2: "EG",
    ISO3: "EGY",
    code: "818",
  },
  {
    label: "El Salvador",
    ISO2: "SV",
    ISO3: "SLV",
    code: "222",
  },
  {
    label: "Equatorial Guinea",
    ISO2: "GQ",
    ISO3: "GNQ",
    code: "226",
  },
  {
    label: "Eritrea",
    ISO2: "ER",
    ISO3: "ERI",
    code: "232",
  },
  {
    label: "Estonia",
    ISO2: "EE",
    ISO3: "EST",
    code: "233",
  },
  {
    label: "Eswatini",
    ISO2: "SZ",
    ISO3: "SWZ",
    code: "748",
  },
  {
    label: "Ethiopia",
    ISO2: "ET",
    ISO3: "ETH",
    code: "231",
  },
  {
    label: "Falkland Islands (Malvinas)",
    ISO2: "FK",
    ISO3: "FLK",
    code: "238",
  },
  {
    label: "Faroe Islands",
    ISO2: "FO",
    ISO3: "FRO",
    code: "234",
  },
  {
    label: "Fiji",
    ISO2: "FJ",
    ISO3: "FJI",
    code: "242",
  },
  {
    label: "Finland",
    ISO2: "FI",
    ISO3: "FIN",
    code: "246",
  },
  {
    label: "France",
    ISO2: "FR",
    ISO3: "FRA",
    code: "250",
  },
  {
    label: "French Guiana",
    ISO2: "GF",
    ISO3: "GUF",
    code: "254",
  },
  {
    label: "French Polynesia",
    ISO2: "PF",
    ISO3: "PYF",
    code: "258",
  },
  {
    label: "French Southern Territories",
    ISO2: "TF",
    ISO3: "ATF",
    code: "260",
  },
  {
    label: "Gabon",
    ISO2: "GA",
    ISO3: "GAB",
    code: "266",
  },
  {
    label: "Gambia",
    ISO2: "GM",
    ISO3: "GMB",
    code: "270",
  },
  {
    label: "Georgia",
    ISO2: "GE",
    ISO3: "GEO",
    code: "268",
  },
  {
    label: "Germany",
    ISO2: "DE",
    ISO3: "DEU",
    code: "276",
  },
  {
    label: "Ghana",
    ISO2: "GH",
    ISO3: "GHA",
    code: "288",
  },
  {
    label: "Gibraltar",
    ISO2: "GI",
    ISO3: "GIB",
    code: "292",
  },
  {
    label: "Greece",
    ISO2: "GR",
    ISO3: "GRC",
    code: "300",
  },
  {
    label: "Greenland",
    ISO2: "GL",
    ISO3: "GRL",
    code: "304",
  },
  {
    label: "Grenada",
    ISO2: "GD",
    ISO3: "GRD",
    code: "308",
  },
  {
    label: "Guadeloupe",
    ISO2: "GP",
    ISO3: "GLP",
    code: "312",
  },
  {
    label: "Guam",
    ISO2: "GU",
    ISO3: "GUM",
    code: "316",
  },
  {
    label: "Guatemala",
    ISO2: "GT",
    ISO3: "GTM",
    code: "320",
  },
  {
    label: "Guernsey",
    ISO2: "GG",
    ISO3: "GGY",
    code: "831",
  },
  {
    label: "Guinea",
    ISO2: "GN",
    ISO3: "GIN",
    code: "324",
  },
  {
    label: "Guinea-Bissau",
    ISO2: "GW",
    ISO3: "GNB",
    code: "624",
  },
  {
    label: "Guyana",
    ISO2: "GY",
    ISO3: "GUY",
    code: "328",
  },
  {
    label: "Haiti",
    ISO2: "HT",
    ISO3: "HTI",
    code: "332",
  },
  {
    label: "Heard Island and McDonald Islands",
    ISO2: "HM",
    ISO3: "HMD",
    code: "334",
  },
  {
    label: "Holy See",
    ISO2: "VA",
    ISO3: "VAT",
    code: "336",
  },
  {
    label: "Honduras",
    ISO2: "HN",
    ISO3: "HND",
    code: "340",
  },
  {
    label: "Hong Kong",
    ISO2: "HK",
    ISO3: "HKG",
    code: "344",
  },
  {
    label: "Hungary",
    ISO2: "HU",
    ISO3: "HUN",
    code: "348",
  },
  {
    label: "Iceland",
    ISO2: "IS",
    ISO3: "ISL",
    code: "352",
  },
  {
    label: "India",
    ISO2: "IN",
    ISO3: "IND",
    code: "356",
  },
  {
    label: "Indonesia",
    ISO2: "ID",
    ISO3: "IDN",
    code: "360",
  },
  {
    label: "Iran (Islamic Republic of)",
    ISO2: "IR",
    ISO3: "IRN",
    code: "364",
  },
  {
    label: "Iraq",
    ISO2: "IQ",
    ISO3: "IRQ",
    code: "368",
  },
  {
    label: "Ireland",
    ISO2: "IE",
    ISO3: "IRL",
    code: "372",
  },
  {
    label: "Isle of Man",
    ISO2: "IM",
    ISO3: "IMN",
    code: "833",
  },
  {
    label: "Israel",
    ISO2: "IL",
    ISO3: "ISR",
    code: "376",
  },
  {
    label: "Italy",
    ISO2: "IT",
    ISO3: "ITA",
    code: "380",
  },
  {
    label: "Jamaica",
    ISO2: "JM",
    ISO3: "JAM",
    code: "388",
  },
  {
    label: "Japan",
    ISO2: "JP",
    ISO3: "JPN",
    code: "392",
  },
  {
    label: "Jersey",
    ISO2: "JE",
    ISO3: "JEY",
    code: "832",
  },
  {
    label: "Jordan",
    ISO2: "JO",
    ISO3: "JOR",
    code: "400",
  },
  {
    label: "Kazakhstan",
    ISO2: "KZ",
    ISO3: "KAZ",
    code: "398",
  },
  {
    label: "Kenya",
    ISO2: "KE",
    ISO3: "KEN",
    code: "404",
  },
  {
    label: "Kiribati",
    ISO2: "KI",
    ISO3: "KIR",
    code: "296",
  },
  {
    label: "Korea (Democratic People's Republic of)",
    ISO2: "KP",
    ISO3: "PRK",
    code: "408",
  },
  {
    label: "Korea, Republic of",
    ISO2: "KR",
    ISO3: "KOR",
    code: "410",
  },
  {
    label: "Kuwait",
    ISO2: "KW",
    ISO3: "KWT",
    code: "414",
  },
  {
    label: "Kyrgyzstan",
    ISO2: "KG",
    ISO3: "KGZ",
    code: "417",
  },
  {
    label: "Lao People's Democratic Republic",
    ISO2: "LA",
    ISO3: "LAO",
    code: "418",
  },
  {
    label: "Latvia",
    ISO2: "LV",
    ISO3: "LVA",
    code: "428",
  },
  {
    label: "Lebanon",
    ISO2: "LB",
    ISO3: "LBN",
    code: "422",
  },
  {
    label: "Lesotho",
    ISO2: "LS",
    ISO3: "LSO",
    code: "426",
  },
  {
    label: "Liberia",
    ISO2: "LR",
    ISO3: "LBR",
    code: "430",
  },
  {
    label: "Libya",
    ISO2: "LY",
    ISO3: "LBY",
    code: "434",
  },
  {
    label: "Liechtenstein",
    ISO2: "LI",
    ISO3: "LIE",
    code: "438",
  },
  {
    label: "Lithuania",
    ISO2: "LT",
    ISO3: "LTU",
    code: "440",
  },
  {
    label: "Luxembourg",
    ISO2: "LU",
    ISO3: "LUX",
    code: "442",
  },
  {
    label: "Macao",
    ISO2: "MO",
    ISO3: "MAC",
    code: "446",
  },
  {
    label: "Madagascar",
    ISO2: "MG",
    ISO3: "MDG",
    code: "450",
  },
  {
    label: "Malawi",
    ISO2: "MW",
    ISO3: "MWI",
    code: "454",
  },
  {
    label: "Malaysia",
    ISO2: "MY",
    ISO3: "MYS",
    code: "458",
  },
  {
    label: "Maldives",
    ISO2: "MV",
    ISO3: "MDV",
    code: "462",
  },
  {
    label: "Mali",
    ISO2: "ML",
    ISO3: "MLI",
    code: "466",
  },
  {
    label: "Malta",
    ISO2: "MT",
    ISO3: "MLT",
    code: "470",
  },
  {
    label: "Marshall Islands",
    ISO2: "MH",
    ISO3: "MHL",
    code: "584",
  },
  {
    label: "Martinique",
    ISO2: "MQ",
    ISO3: "MTQ",
    code: "474",
  },
  {
    label: "Mauritania",
    ISO2: "MR",
    ISO3: "MRT",
    code: "478",
  },
  {
    label: "Mauritius",
    ISO2: "MU",
    ISO3: "MUS",
    code: "480",
  },
  {
    label: "Mayotte",
    ISO2: "YT",
    ISO3: "MYT",
    code: "175",
  },
  {
    label: "Mexico",
    ISO2: "MX",
    ISO3: "MEX",
    code: "484",
  },
  {
    label: "Micronesia (Federated States of)",
    ISO2: "FM",
    ISO3: "FSM",
    code: "583",
  },
  {
    label: "Moldova, Republic of",
    ISO2: "MD",
    ISO3: "MDA",
    code: "498",
  },
  {
    label: "Monaco",
    ISO2: "MC",
    ISO3: "MCO",
    code: "492",
  },
  {
    label: "Mongolia",
    ISO2: "MN",
    ISO3: "MNG",
    code: "496",
  },
  {
    label: "Montenegro",
    ISO2: "ME",
    ISO3: "MNE",
    code: "499",
  },
  {
    label: "Montserrat",
    ISO2: "MS",
    ISO3: "MSR",
    code: "500",
  },
  {
    label: "Morocco",
    ISO2: "MA",
    ISO3: "MAR",
    code: "504",
  },
  {
    label: "Mozambique",
    ISO2: "MZ",
    ISO3: "MOZ",
    code: "508",
  },
  {
    label: "Myanmar",
    ISO2: "MM",
    ISO3: "MMR",
    code: "104",
  },
  {
    label: "Namibia",
    ISO2: "NA",
    ISO3: "NAM",
    code: "516",
  },
  {
    label: "Nauru",
    ISO2: "NR",
    ISO3: "NRU",
    code: "520",
  },
  {
    label: "Nepal",
    ISO2: "NP",
    ISO3: "NPL",
    code: "524",
  },
  {
    label: "Netherlands",
    ISO2: "NL",
    ISO3: "NLD",
    code: "528",
  },
  {
    label: "New Caledonia",
    ISO2: "NC",
    ISO3: "NCL",
    code: "540",
  },
  {
    label: "New Zealand",
    ISO2: "NZ",
    ISO3: "NZL",
    code: "554",
  },
  {
    label: "Nicaragua",
    ISO2: "NI",
    ISO3: "NIC",
    code: "558",
  },
  {
    label: "Niger",
    ISO2: "NE",
    ISO3: "NER",
    code: "562",
  },
  {
    label: "Nigeria",
    ISO2: "NG",
    ISO3: "NGA",
    code: "566",
  },
  {
    label: "Niue",
    ISO2: "NU",
    ISO3: "NIU",
    code: "570",
  },
  {
    label: "Norfolk Island",
    ISO2: "NF",
    ISO3: "NFK",
    code: "574",
  },
  {
    label: "North Macedonia",
    ISO2: "MK",
    ISO3: "MKD",
    code: "807",
  },
  {
    label: "Northern Mariana Islands",
    ISO2: "MP",
    ISO3: "MNP",
    code: "580",
  },
  {
    label: "Norway",
    ISO2: "NO",
    ISO3: "NOR",
    code: "578",
  },
  {
    label: "Oman",
    ISO2: "OM",
    ISO3: "OMN",
    code: "512",
  },
  {
    label: "Pakistan",
    ISO2: "PK",
    ISO3: "PAK",
    code: "586",
  },
  {
    label: "Palau",
    ISO2: "PW",
    ISO3: "PLW",
    code: "585",
  },
  {
    label: "Palestine, State of",
    ISO2: "PS",
    ISO3: "PSE",
    code: "275",
  },
  {
    label: "Panama",
    ISO2: "PA",
    ISO3: "PAN",
    code: "591",
  },
  {
    label: "Papua New Guinea",
    ISO2: "PG",
    ISO3: "PNG",
    code: "598",
  },
  {
    label: "Paraguay",
    ISO2: "PY",
    ISO3: "PRY",
    code: "600",
  },
  {
    label: "Peru",
    ISO2: "PE",
    ISO3: "PER",
    code: "604",
  },
  {
    label: "Philippines",
    ISO2: "PH",
    ISO3: "PHL",
    code: "608",
  },
  {
    label: "Pitcairn",
    ISO2: "PN",
    ISO3: "PCN",
    code: "612",
  },
  {
    label: "Poland",
    ISO2: "PL",
    ISO3: "POL",
    code: "616",
  },
  {
    label: "Portugal",
    ISO2: "PT",
    ISO3: "PRT",
    code: "620",
  },
  {
    label: "Puerto Rico",
    ISO2: "PR",
    ISO3: "PRI",
    code: "630",
  },
  {
    label: "Qatar",
    ISO2: "QA",
    ISO3: "QAT",
    code: "634",
  },
  {
    label: "Réunion",
    ISO2: "RE",
    ISO3: "REU",
    code: "638",
  },
  {
    label: "Romania",
    ISO2: "RO",
    ISO3: "ROU",
    code: "642",
  },
  {
    label: "Russian Federation",
    ISO2: "RU",
    ISO3: "RUS",
    code: "643",
  },
  {
    label: "Rwanda",
    ISO2: "RW",
    ISO3: "RWA",
    code: "646",
  },
  {
    label: "Saint Barthélemy",
    ISO2: "BL",
    ISO3: "BLM",
    code: "652",
  },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    ISO2: "SH",
    ISO3: "SHN",
    code: "654",
  },
  {
    label: "Saint Kitts and Nevis",
    ISO2: "KN",
    ISO3: "KNA",
    code: "659",
  },
  {
    label: "Saint Lucia",
    ISO2: "LC",
    ISO3: "LCA",
    code: "662",
  },
  {
    label: "Saint Martin (French part)",
    ISO2: "MF",
    ISO3: "MAF",
    code: "663",
  },
  {
    label: "Saint Pierre and Miquelon",
    ISO2: "PM",
    ISO3: "SPM",
    code: "666",
  },
  {
    label: "Saint Vincent and the Grenadines",
    ISO2: "VC",
    ISO3: "VCT",
    code: "670",
  },
  {
    label: "Samoa",
    ISO2: "WS",
    ISO3: "WSM",
    code: "882",
  },
  {
    label: "San Marino",
    ISO2: "SM",
    ISO3: "SMR",
    code: "674",
  },
  {
    label: "Sao Tome and Principe",
    ISO2: "ST",
    ISO3: "STP",
    code: "678",
  },
  {
    label: "Saudi Arabia",
    ISO2: "SA",
    ISO3: "SAU",
    code: "682",
  },
  {
    label: "Senegal",
    ISO2: "SN",
    ISO3: "SEN",
    code: "686",
  },
  {
    label: "Serbia",
    ISO2: "RS",
    ISO3: "SRB",
    code: "688",
  },
  {
    label: "Seychelles",
    ISO2: "SC",
    ISO3: "SYC",
    code: "690",
  },
  {
    label: "Sierra Leone",
    ISO2: "SL",
    ISO3: "SLE",
    code: "694",
  },
  {
    label: "Singapore",
    ISO2: "SG",
    ISO3: "SGP",
    code: "702",
  },
  {
    label: "Sint Maarten (Dutch part)",
    ISO2: "SX",
    ISO3: "SXM",
    code: "534",
  },
  {
    label: "Slovakia",
    ISO2: "SK",
    ISO3: "SVK",
    code: "703",
  },
  {
    label: "Slovenia",
    ISO2: "SI",
    ISO3: "SVN",
    code: "705",
  },
  {
    label: "Solomon Islands",
    ISO2: "SB",
    ISO3: "SLB",
    code: "090",
  },
  {
    label: "Somalia",
    ISO2: "SO",
    ISO3: "SOM",
    code: "706",
  },
  {
    label: "South Africa",
    ISO2: "ZA",
    ISO3: "ZAF",
    code: "710",
  },
  {
    label: "South Georgia and the South Sandwich Islands",
    ISO2: "GS",
    ISO3: "SGS",
    code: "239",
  },
  {
    label: "South Sudan",
    ISO2: "SS",
    ISO3: "SSD",
    code: "728",
  },
  {
    label: "Spain",
    ISO2: "ES",
    ISO3: "ESP",
    code: "724",
  },
  {
    label: "Sri Lanka",
    ISO2: "LK",
    ISO3: "LKA",
    code: "144",
  },
  {
    label: "Sudan",
    ISO2: "SD",
    ISO3: "SDN",
    code: "729",
  },
  {
    label: "Surilabel",
    ISO2: "SR",
    ISO3: "SUR",
    code: "740",
  },
  {
    label: "Svalbard and Jan Mayen",
    ISO2: "SJ",
    ISO3: "SJM",
    code: "744",
  },
  {
    label: "Sweden",
    ISO2: "SE",
    ISO3: "SWE",
    code: "752",
  },
  {
    label: "Switzerland",
    ISO2: "CH",
    ISO3: "CHE",
    code: "756",
  },
  {
    label: "Syrian Arab Republic",
    ISO2: "SY",
    ISO3: "SYR",
    code: "760",
  },
  {
    label: "Taiwan, Province of China",
    ISO2: "TW",
    ISO3: "TWN",
    code: "158",
  },
  {
    label: "Tajikistan",
    ISO2: "TJ",
    ISO3: "TJK",
    code: "762",
  },
  {
    label: "Tanzania, United Republic of",
    ISO2: "TZ",
    ISO3: "TZA",
    code: "834",
  },
  {
    label: "Thailand",
    ISO2: "TH",
    ISO3: "THA",
    code: "764",
  },
  {
    label: "Timor-Leste",
    ISO2: "TL",
    ISO3: "TLS",
    code: "626",
  },
  {
    label: "Togo",
    ISO2: "TG",
    ISO3: "TGO",
    code: "768",
  },
  {
    label: "Tokelau",
    ISO2: "TK",
    ISO3: "TKL",
    code: "772",
  },
  {
    label: "Tonga",
    ISO2: "TO",
    ISO3: "TON",
    code: "776",
  },
  {
    label: "Trinidad and Tobago",
    ISO2: "TT",
    ISO3: "TTO",
    code: "780",
  },
  {
    label: "Tunisia",
    ISO2: "TN",
    ISO3: "TUN",
    code: "788",
  },
  {
    label: "Turkey",
    ISO2: "TR",
    ISO3: "TUR",
    code: "792",
  },
  {
    label: "Turkmenistan",
    ISO2: "TM",
    ISO3: "TKM",
    code: "795",
  },
  {
    label: "Turks and Caicos Islands",
    ISO2: "TC",
    ISO3: "TCA",
    code: "796",
  },
  {
    label: "Tuvalu",
    ISO2: "TV",
    ISO3: "TUV",
    code: "798",
  },
  {
    label: "Uganda",
    ISO2: "UG",
    ISO3: "UGA",
    code: "800",
  },
  {
    label: "Ukraine",
    ISO2: "UA",
    ISO3: "UKR",
    code: "804",
  },
  {
    label: "United Arab Emirates",
    ISO2: "AE",
    ISO3: "ARE",
    code: "784",
  },
  {
    label: "United Kingdom of Great Britain and Northern Ireland",
    ISO2: "GB",
    ISO3: "GBR",
    code: "826",
  },
  {
    label: "United States of America",
    ISO2: "US",
    ISO3: "USA",
    code: "840",
  },
  {
    label: "United States Minor Outlying Islands",
    ISO2: "UM",
    ISO3: "UMI",
    code: "581",
  },
  {
    label: "Uruguay",
    ISO2: "UY",
    ISO3: "URY",
    code: "858",
  },
  {
    label: "Uzbekistan",
    ISO2: "UZ",
    ISO3: "UZB",
    code: "860",
  },
  {
    label: "Vanuatu",
    ISO2: "VU",
    ISO3: "VUT",
    code: "548",
  },
  {
    label: "Venezuela (Bolivarian Republic of)",
    ISO2: "VE",
    ISO3: "VEN",
    code: "862",
  },
  {
    label: "Viet Nam",
    ISO2: "VN",
    ISO3: "VNM",
    code: "704",
  },
  {
    label: "Virgin Islands (British)",
    ISO2: "VG",
    ISO3: "VGB",
    code: "092",
  },
  {
    label: "Virgin Islands (U.S.)",
    ISO2: "VI",
    ISO3: "VIR",
    code: "850",
  },
  {
    label: "Wallis and Futuna",
    ISO2: "WF",
    ISO3: "WLF",
    code: "876",
  },
  {
    label: "Western Sahara",
    ISO2: "EH",
    ISO3: "ESH",
    code: "732",
  },
  {
    label: "Yemen",
    ISO2: "YE",
    ISO3: "YEM",
    code: "887",
  },
  {
    label: "Zambia",
    ISO2: "ZM",
    ISO3: "ZMB",
    code: "894",
  },
  {
    label: "Zimbabwe",
    ISO2: "ZW",
    ISO3: "ZWE",
    code: "716",
  },
];

export default countries;