import { ModelInit, MutableModel, PersistentModelConstructor } from "@aws-amplify/datastore";





export declare class Spv {
  readonly id: string;
  readonly spvId: string;
  readonly identityId?: string | null;
  readonly spv_address_city?: string | null;
  readonly spv_address_number?: string | null;
  readonly spv_address_postalcode?: string | null;
  readonly spv_address_refinment?: string | null;
  readonly spv_articles_of_association_attachment?: string | null;
  readonly spv_shareholder_list_attachment?: string | null;
  readonly spv_director_list_attachment?: string | null;
  readonly spv_country?: string | null;
  readonly spv_email?: string | null;
  readonly spv_industry?: string | null;
  readonly spv_industry_code?: string | null;
  readonly spv_logo?: string | null;
  readonly spv_name?: string | null;
  readonly spv_register_number?: string | null;
  readonly spv_trading_name?: string | null;
  readonly spv_type?: string | null;
  readonly spv_website?: string | null;
  readonly spv_address_street?: string | null;
  readonly createdAt?: string | null;
  readonly spv_date_of_incorporation?: string | null;
  readonly spv_registration_cert_attachment?: string | null;
  readonly spv_duns_number?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Spv>);
  static copyOf(source: Spv, mutator: (draft: MutableModel<Spv>) => MutableModel<Spv> | void): Spv;
}

export declare class Bank {
  readonly id: string;
  readonly bankId?: string | null;
  readonly buyerId?: string | null;
  readonly supplierId?: string | null;
  readonly investorId?: string | null;
  readonly identityId?: string | null;
  readonly account_statement_attachment?: string | null;
  readonly balance?: string | null;
  readonly balance_available?: string | null;
  readonly bank_account_name?: string | null;
  readonly bank_account_number?: string | null;
  readonly bank_account_sortcode?: string | null;
  readonly bank_address_city?: string | null;
  readonly bank_address_number?: string | null;
  readonly bank_address_postalcode?: string | null;
  readonly bank_address_refinment?: string | null;
  readonly bank_address_street?: string | null;
  readonly bank_branch?: string | null;
  readonly bank_country?: string | null;
  readonly bank_name?: string | null;
  readonly bank_routing_number?: string | null;
  readonly bank_status?: string | null;
  readonly bic_swift_code?: string | null;
  readonly createdAt?: string | null;
  readonly iban?: string | null;
  readonly iso_currency_code?: string | null;
  readonly overdraft?: string | null;
  readonly payments_incoming?: string | null;
  readonly payments_outgoing?: string | null;
  readonly pre_auth_amount?: string | null;
  readonly reporting_end_date?: string | null;
  readonly reporting_start_date?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Bank>);
  static copyOf(source: Bank, mutator: (draft: MutableModel<Bank>) => MutableModel<Bank> | void): Bank;
}

export declare class Broker {
  readonly id: string;
  readonly brokerId: string;
  readonly identityId?: string | null;
  readonly broker_address_city?: string | null;
  readonly broker_address_number?: string | null;
  readonly broker_address_postalcode?: string | null;
  readonly broker_address_refinment?: string | null;
  readonly broker_articles_of_association_attachment?: string | null;
  readonly broker_shareholder_list_attachment?: string | null;
  readonly broker_director_list_attachment?: string | null;
  readonly broker_country?: string | null;
  readonly broker_email?: string | null;
  readonly broker_industry?: string | null;
  readonly broker_industry_code?: string | null;
  readonly broker_logo?: string | null;
  readonly broker_name?: string | null;
  readonly broker_register_number?: string | null;
  readonly broker_trading_name?: string | null;
  readonly broker_type?: string | null;
  readonly broker_website?: string | null;
  readonly broker_address_street?: string | null;
  readonly createdAt?: string | null;
  readonly broker_date_of_incorporation?: string | null;
  readonly broker_registration_cert_attachment?: string | null;
  readonly broker_duns_number?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Broker>);
  static copyOf(source: Broker, mutator: (draft: MutableModel<Broker>) => MutableModel<Broker> | void): Broker;
}

export declare class Buyer {
  readonly id: string;
  readonly buyerId: string;
  readonly supplierId?: (string | null)[] | null;
  readonly investorId?: string | null;
  readonly identityId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly buyer_address_city?: string | null;
  readonly buyer_address_number?: string | null;
  readonly buyer_address_postalcode?: string | null;
  readonly buyer_address_refinment?: string | null;
  readonly buyer_address_street?: string | null;
  readonly buyer_name?: string | null;
  readonly buyer_trading_name?: string | null;
  readonly buyer_country?: string | null;
  readonly buyer_country_year_of_rating_downgrade?: string | null;
  readonly buyer_country_year_of_rating_downgrade_risk?: string | null;
  readonly buyer_contact_name?: string | null;
  readonly buyer_contact_email?: string | null;
  readonly buyer_contact_phone?: string | null;
  readonly buyer_contact_position?: string | null;
  readonly buyer_website?: string | null;
  readonly createdAt?: string | null;
  readonly buyer_currency?: string | null;
  readonly buyer_date_of_incorporation?: string | null;
  readonly buyer_date_of_incorporation_risk?: string | null;
  readonly buyer_description?: string | null;
  readonly buyer_existing_disputes?: string | null;
  readonly buyer_existing_disputes_risk?: string | null;
  readonly buyer_existing_disputes_source?: string | null;
  readonly buyer_finance_department_contact_exists?: string | null;
  readonly buyer_finance_department_contact_email?: string | null;
  readonly buyer_field_visit_conducted?: string | null;
  readonly buyer_incoterms?: string | null;
  readonly buyer_industry?: string | null;
  readonly buyer_industry_code?: string | null;
  readonly buyer_invoices_paid_on_time?: string | null;
  readonly buyer_invoices_paid_on_time_risk?: string | null;
  readonly buyer_invoices_past_due?: string | null;
  readonly buyer_invoices_past_due_30_days?: string | null;
  readonly buyer_invoices_past_due_30_days_risk?: string | null;
  readonly buyer_invoices_past_due_60_days?: string | null;
  readonly buyer_invoices_past_due_60_days_risk?: string | null;
  readonly buyer_invoices_past_due_90_days?: string | null;
  readonly buyer_insurance_name?: string | null;
  readonly buyer_insurance_rating?: string | null;
  readonly buyer_insurance_status?: string | null;
  readonly buyer_insurance_status_risk?: string | null;
  readonly buyer_one_off_ipu_attachment?: string | null;
  readonly buyer_loan_request_amount?: string | null;
  readonly buyer_loan_approved_amount?: string | null;
  readonly buyer_loan_advance_rate?: string | null;
  readonly buyer_loan_collateral?: string | null;
  readonly buyer_loan_covenants?: string | null;
  readonly buyer_loan_transaction_fee?: string | null;
  readonly buyer_loan_discount_fee?: string | null;
  readonly buyer_loan_spv_fee?: string | null;
  readonly buyer_loan_broker_fee?: string | null;
  readonly buyer_loan_purpose?: string | null;
  readonly buyer_loan_rate?: string | null;
  readonly buyer_loan_type?: string | null;
  readonly buyer_logo?: string | null;
  readonly buyer_next_year_projected_transaction_amount?: string | null;
  readonly buyer_next_year_projected_number_invoices?: string | null;
  readonly buyer_payment_terms?: string | null;
  readonly buyer_previous_year_transaction_amount?: string | null;
  readonly buyer_previous_year_number_invoices?: string | null;
  readonly buyer_reporting_year?: string | null;
  readonly buyer_reporting_year_transaction_amount?: string | null;
  readonly buyer_reporting_year_number_invoices?: string | null;
  readonly buyer_reporting_year_number_invoices_risk?: string | null;
  readonly buyer_sample_trading_docs_attachment?: string | null;
  readonly buyer_sold_goods_description?: string | null;
  readonly buyer_supplier_year_business_relation_started?: string | null;
  readonly buyer_supplier_year_business_relation_started_risk?: string | null;
  readonly buyer_status?: string | null;
  readonly buyer_type?: string | null;
  readonly buyer_use_of_goods_purchased?: string | null;
  readonly buyer_use_of_goods_purchased_risk?: string | null;
  readonly buyer_registration_cert_attachment?: string | null;
  readonly buyer_shareholder_list_attachment?: string | null;
  readonly buyer_director_list_attachment?: string | null;
  readonly buyer_articles_of_association_attachment?: string | null;
  readonly buyer_duns_number?: string | null;
  readonly sortkey?: string | null;
  readonly userId?: string[] | null;
  constructor(init: ModelInit<Buyer>);
  static copyOf(source: Buyer, mutator: (draft: MutableModel<Buyer>) => MutableModel<Buyer> | void): Buyer;
}

export declare class Bookkeeping {
  readonly id: string;
  readonly bookkeeping_status?: string | null;
  readonly bookkeepingId?: string | null;
  readonly buyerId?: string | null;
  readonly supplierId?: string | null;
  readonly investorId?: string | null;
  readonly identityId?: string | null;
  readonly requestId?: string | null;
  readonly transactionId?: string | null;
  readonly createdAt?: string | null;
  readonly sortkey?: string | null;
  readonly invoiceId_3party?: string | null;
  readonly invoiceurl_3party?: string | null;
  readonly invoicepdfurl_3party?: string | null;
  constructor(init: ModelInit<Bookkeeping>);
  static copyOf(source: Bookkeeping, mutator: (draft: MutableModel<Bookkeeping>) => MutableModel<Bookkeeping> | void): Bookkeeping;
}

export declare class Director {
  readonly id: string;
  readonly directorId: string;
  readonly supplierId?: string | null;
  readonly buyerId?: string | null;
  readonly investorId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly identityId?: string | null;
  readonly director_appointment_date?: string | null;
  readonly director_country_of_residence?: string | null;
  readonly director_date_of_birth?: string | null;
  readonly director_email?: string | null;
  readonly director_id_attachment?: string | null;
  readonly director_id_expiry_date?: string | null;
  readonly director_id_issue_date?: string | null;
  readonly director_id_issuer_country?: string | null;
  readonly director_id_issuer_state?: string | null;
  readonly director_id_number?: string | null;
  readonly director_id_type?: string | null;
  readonly director_jobtitle?: string | null;
  readonly director_name?: string | null;
  readonly director_nationality?: string | null;
  readonly director_pep_status?: string | null;
  readonly director_phone_number?: string | null;
  readonly director_poa_attachment?: string | null;
  readonly director_ubo_status?: string | null;
  readonly createdAt?: string | null;
  readonly director_status?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Director>);
  static copyOf(source: Director, mutator: (draft: MutableModel<Director>) => MutableModel<Director> | void): Director;
}

export declare class Document {
  readonly id: string;
  readonly documentId?: string | null;
  readonly userId: string;
  readonly identityId?: string | null;
  readonly bankId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly buyerId?: string | null;
  readonly directorId?: string | null;
  readonly financialsId?: string | null;
  readonly investorId?: string | null;
  readonly requestId?: string | null;
  readonly supplierId?: string | null;
  readonly transactionId?: string | null;
  readonly uboId?: string | null;
  readonly document_type?: string | null;
  readonly document_attachment?: string | null;
  readonly createdAt?: string | null;
  readonly sortkey?: string | null;
  constructor(init: ModelInit<Document>);
  static copyOf(source: Document, mutator: (draft: MutableModel<Document>) => MutableModel<Document> | void): Document;
}

export declare class Financials {
  readonly id: string;
  readonly financialsId: string;
  readonly supplierId?: string | null;
  readonly buyerId?: string | null;
  readonly investorId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly identityId?: string | null;
  readonly financials_attachment?: string | null;
  readonly balance_sheet_attachment?: string | null;
  readonly income_statement_attachment?: string | null;
  readonly current_assets?: string | null;
  readonly cash_flow?: string | null;
  readonly cash_flow_from_operating_activities?: string | null;
  readonly cash_flow_from_operating_activities_risk?: string | null;
  readonly current_long_term_debt?: string | null;
  readonly current_liabilities?: string | null;
  readonly gross_margin?: string | null;
  readonly operating_income?: string | null;
  readonly other_expenses?: string | null;
  readonly ebt?: string | null;
  readonly ebitda?: string | null;
  readonly current_ratio?: string | null;
  readonly current_ratio_risk?: string | null;
  readonly debt_equity_ratio?: string | null;
  readonly debt_ebitda_ratio?: string | null;
  readonly inventory_turnover?: string | null;
  readonly inventory_turnover_risk?: string | null;
  readonly inventory_turnover_trend?: string | null;
  readonly inventory_turnover_trend_risk?: string | null;
  readonly inventory_cost_of_goods_sold_ratio?: string | null;
  readonly inventory_cost_of_goods_sold_ratio_risk?: string | null;
  readonly inventory_buyer_transaction_amount_ratio?: string | null;
  readonly inventory_buyer_transaction_amount_ratio_risk?: string | null;
  readonly interest_coverage?: string | null;
  readonly interest_coverage_risk?: string | null;
  readonly income_tax_expense?: string | null;
  readonly total_liabilities_and_equity?: string | null;
  readonly cash?: string | null;
  readonly marketable_securities?: string | null;
  readonly accounts_receivable?: string | null;
  readonly inventory?: string | null;
  readonly inventory_beginning?: string | null;
  readonly inventory_end?: string | null;
  readonly property?: string | null;
  readonly goodwill?: string | null;
  readonly other_current_assets?: string | null;
  readonly other_non_current_assets?: string | null;
  readonly accumulated_depreciation?: string | null;
  readonly net_operating_loss?: string | null;
  readonly total_assets?: string | null;
  readonly short_term_debt?: string | null;
  readonly accounts_payable?: string | null;
  readonly accured_expenses?: string | null;
  readonly unearned_revenue?: string | null;
  readonly long_term_debt?: string | null;
  readonly other_current_liabilities?: string | null;
  readonly other_long_term_liabilities?: string | null;
  readonly income_tax_payable?: string | null;
  readonly dividends_payable?: string | null;
  readonly total_liabilities?: string | null;
  readonly common_stock?: string | null;
  readonly preferred_stock?: string | null;
  readonly paid_in_capital?: string | null;
  readonly retained_earnings?: string | null;
  readonly total_equity?: string | null;
  readonly equity_book_value?: string | null;
  readonly equity_market_value?: string | null;
  readonly equity_net_operating_loss_ratio?: string | null;
  readonly equity_net_operating_loss_ratio_risk?: string | null;
  readonly sales?: string | null;
  readonly sales_risk?: string | null;
  readonly cost_of_goods_sold?: string | null;
  readonly operating_expenses?: string | null;
  readonly marketing_expenses?: string | null;
  readonly bad_debt_expenses?: string | null;
  readonly createdAt?: string | null;
  readonly ebit?: string | null;
  readonly interest_expenses?: string | null;
  readonly depreciation_expenses?: string | null;
  readonly sale_purchase_of_fixed_asset?: string | null;
  readonly extraordinary_income?: string | null;
  readonly tax_expenses?: string | null;
  readonly net_profit?: string | null;
  readonly net_profit_risk?: string | null;
  readonly net_profit_previous_year?: string | null;
  readonly financials_rating?: string | null;
  readonly financials_reporting_period?: string | null;
  readonly working_capital?: string | null;
  readonly financials_status?: string | null;
  readonly financials_status_risk?: string | null;
  readonly financials_denomination?: string | null;
  readonly userId: string;
  readonly sortkey?: string | null;
  constructor(init: ModelInit<Financials>);
  static copyOf(source: Financials, mutator: (draft: MutableModel<Financials>) => MutableModel<Financials> | void): Financials;
}

export declare class Investor {
  readonly id: string;
  readonly investorId: string;
  readonly identityId?: string | null;
  readonly investor_address_city?: string | null;
  readonly investor_address_number?: string | null;
  readonly investor_address_postalcode?: string | null;
  readonly investor_address_refinment?: string | null;
  readonly investor_articles_of_association_attachment?: string | null;
  readonly investor_shareholder_list_attachment?: string | null;
  readonly investor_director_list_attachment?: string | null;
  readonly investor_country?: string | null;
  readonly investor_email?: string | null;
  readonly investor_industry?: string | null;
  readonly investor_industry_code?: string | null;
  readonly investor_logo?: string | null;
  readonly investor_name?: string | null;
  readonly investor_register_number?: string | null;
  readonly investor_trading_name?: string | null;
  readonly investor_type?: string | null;
  readonly investor_website?: string | null;
  readonly investor_address_street?: string | null;
  readonly createdAt?: string | null;
  readonly investor_date_of_incorporation?: string | null;
  readonly investor_registration_cert_attachment?: string | null;
  readonly investor_duns_number?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Investor>);
  static copyOf(source: Investor, mutator: (draft: MutableModel<Investor>) => MutableModel<Investor> | void): Investor;
}

export declare class Originate {
  readonly id: string;
  readonly sortkey: string;
  readonly userId: string;
  constructor(init: ModelInit<Originate>);
  static copyOf(source: Originate, mutator: (draft: MutableModel<Originate>) => MutableModel<Originate> | void): Originate;
}

export declare class Plaidauth {
  readonly id: string;
  readonly accessToken1?: string | null;
  readonly accessToken2?: string | null;
  readonly account_id1?: string | null;
  readonly account_id2?: string | null;
  readonly updatedAt?: string | null;
  readonly createdAt?: string | null;
  constructor(init: ModelInit<Plaidauth>);
  static copyOf(source: Plaidauth, mutator: (draft: MutableModel<Plaidauth>) => MutableModel<Plaidauth> | void): Plaidauth;
}

export declare class Request {
  readonly id: string;
  readonly requestId: string;
  readonly buyerId?: string | null;
  readonly supplierId?: string | null;
  readonly investorId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly identityId?: string | null;
  readonly buyer_name?: string | null;
  readonly supplier_name?: string | null;
  readonly investor_email?: string | null;
  readonly advance_rate?: string | null;
  readonly spv_fee_rate?: string | null;
  readonly spv_fee_amount?: string | null;
  readonly broker_fee_rate?: string | null;
  readonly broker_fee_amount?: string | null;
  readonly discount_fee_rate?: string | null;
  readonly discount_fee_amount?: string | null;
  readonly transaction_fee_rate?: string | null;
  readonly transaction_fee_amount?: string | null;
<<<<<<< HEAD
=======
  readonly base_rate?: string | null;
>>>>>>> 8450a79011d666b00a743fa835391f6f3ce2f367
  readonly purchase_order_amount?: string | null;
  readonly purchase_order_attachment?: string | null;
  readonly purchase_order_date?: string | null;
  readonly purchase_order_number?: string | null;
  readonly sold_goods_description?: string | null;
  readonly invoice_amount?: string | null;
  readonly invoice_currency?: string | null;
  readonly invoice_payout_date?: string | null;
  readonly invoice_date?: string | null;
  readonly invoice_due_date?: string | null;
  readonly invoice_attachment?: string | null;
  readonly invoice_number?: string | null;
  readonly offer_notice_attachment?: string | null;
  readonly ipu_attachment?: string | null;
  readonly ipu_signature_name?: string | null;
  readonly ipu_signature_email?: string | null;
  readonly ipu_e_signatureId?: string | null;
  readonly cargo_insurance_name?: string | null;
  readonly cargo_insurance_attachment?: string | null;
  readonly bill_of_lading_no?: string | null;
  readonly bill_of_lading_attachment?: string | null;
  readonly container_no?: string | null;
  readonly packing_list_attachment?: string | null;
  readonly createdAt?: string | null;
  readonly payout_date?: string | null;
  readonly payback_date?: string | null;
  readonly request_status?: string | null;
  readonly bookkeeping_status?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Request>);
  static copyOf(source: Request, mutator: (draft: MutableModel<Request>) => MutableModel<Request> | void): Request;
}

export declare class SOFR {
  readonly id: string;
<<<<<<< HEAD
=======
  readonly SOFR?: string | null;
>>>>>>> 8450a79011d666b00a743fa835391f6f3ce2f367
  readonly SOFRM1?: string | null;
  readonly SOFRM3?: string | null;
  readonly updatedAt?: string | null;
  readonly createdAt?: string | null;
  constructor(init: ModelInit<SOFR>);
  static copyOf(source: SOFR, mutator: (draft: MutableModel<SOFR>) => MutableModel<SOFR> | void): SOFR;
}

export declare class Supplier {
  readonly id: string;
  readonly supplierId: string;
  readonly identityId?: string | null;
  readonly brokerId?: string | null;
  readonly supplier_address_city?: string | null;
  readonly supplier_address_number?: string | null;
  readonly supplier_address_postalcode?: string | null;
  readonly supplier_address_refinment?: string | null;
  readonly supplier_articles_of_association_attachment?: string | null;
  readonly supplier_shareholder_list_attachment?: string | null;
  readonly supplier_description?: string | null;
  readonly supplier_director_list_attachment?: string | null;
  readonly supplier_country?: string | null;
  readonly supplier_industry?: string | null;
  readonly supplier_industry_code?: string | null;
  readonly supplier_logo?: string | null;
  readonly supplier_name?: string | null;
  readonly supplier_register_number?: string | null;
  readonly supplier_register_number_type?: string | null;
  readonly supplier_trading_name?: string | null;
  readonly supplier_type?: string | null;
  readonly supplier_website?: string | null;
  readonly supplier_address_street?: string | null;
  readonly createdAt?: string | null;
  readonly supplier_date_of_incorporation?: string | null;
  readonly supplier_registration_cert_attachment?: string | null;
  readonly supplier_duns_number?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<Supplier>);
  static copyOf(source: Supplier, mutator: (draft: MutableModel<Supplier>) => MutableModel<Supplier> | void): Supplier;
}

export declare class Transaction {
  readonly id: string;
  readonly transactionId: string;
  readonly buyerId?: string | null;
  readonly supplierId?: string | null;
  readonly investorId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly identityId?: string | null;
  readonly authorized_date?: string | null;
  readonly category?: string | null;
  readonly iso_currency_code?: string | null;
  readonly location?: string | null;
  readonly merchant_name?: string | null;
  readonly payment_channel?: string | null;
  readonly pending?: string | null;
  readonly recipient_account_name?: string | null;
  readonly recipient_bank_account_number?: string | null;
  readonly recipient_bank_account_sortcode?: string | null;
  readonly recipient_bank_address_city?: string | null;
  readonly recipient_bank_address_number?: string | null;
  readonly recipient_bank_address_postalcode?: string | null;
  readonly recipient_bank_address_refinment?: string | null;
  readonly recipient_bank_address_street?: string | null;
  readonly recipient_bank_branch?: string | null;
  readonly recipient_bank_country?: string | null;
  readonly recipient_bank_name?: string | null;
  readonly recipient_bank_routing_number?: string | null;
  readonly recipient_bic_swift_code?: string | null;
  readonly recipient_iban?: string | null;
  readonly recipientaccountId?: string | null;
  readonly sender_account_name?: string | null;
  readonly sender_bank_account_number?: string | null;
  readonly sender_bank_account_sortcode?: string | null;
  readonly sender_bank_branch?: string | null;
  readonly sender_bank_name?: string | null;
  readonly sender_bank_routing_number?: string | null;
  readonly sender_bic_swift_code?: string | null;
  readonly sender_iban?: string | null;
  readonly senderaccountId?: string | null;
  readonly transaction_code?: string | null;
  readonly transaction_date?: string | null;
  readonly transaction_description?: string | null;
  readonly transaction_exchange_rate?: string | null;
  readonly transaction_exchange_rate_fee?: string | null;
  readonly transaction_source_amount?: string | null;
  readonly transaction_source_currency?: string | null;
  readonly transaction_status?: string | null;
  readonly transaction_target_amount?: string | null;
  readonly transaction_target_currency?: string | null;
  readonly userId: string;
  readonly sortkey?: string | null;
  constructor(init: ModelInit<Transaction>);
  static copyOf(source: Transaction, mutator: (draft: MutableModel<Transaction>) => MutableModel<Transaction> | void): Transaction;
}

export declare class UBO {
  readonly id: string;
  readonly uboId: string;
  readonly supplierId?: string | null;
  readonly buyerId?: string | null;
  readonly investorId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly identityId?: string | null;
  readonly ubo_appointment_date?: string | null;
  readonly ubo_country_of_residence?: string | null;
  readonly ubo_date_of_birth?: string | null;
  readonly ubo_email?: string | null;
  readonly ubo_id_attachment?: string | null;
  readonly ubo_id_expiry_date?: string | null;
  readonly ubo_id_issue_date?: string | null;
  readonly ubo_id_issuer_country?: string | null;
  readonly ubo_id_issuer_state?: string | null;
  readonly ubo_id_number?: string | null;
  readonly ubo_id_type?: string | null;
  readonly ubo_jobtitle?: string | null;
  readonly ubo_name?: string | null;
  readonly ubo_nationality?: string | null;
  readonly ubo_ownership_percentage?: string | null;
  readonly ubo_pep_status?: string | null;
  readonly ubo_phone_number?: string | null;
  readonly ubo_poa_attachment?: string | null;
  readonly createdAt?: string | null;
  readonly ubo_status?: string | null;
  readonly sortkey?: string | null;
  readonly userId: string;
  constructor(init: ModelInit<UBO>);
  static copyOf(source: UBO, mutator: (draft: MutableModel<UBO>) => MutableModel<UBO> | void): UBO;
}

export declare class Usergroup {
  readonly id: string;
  readonly groupId: string;
  readonly userId?: string | null;
  readonly user_name?: string | null;
  readonly investorId?: string | null;
  readonly supplierId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly sub?: string | null;
  readonly identityId?: string | null;
  readonly group_type?: string | null;
  readonly group_name?: string | null;
  readonly group_contact_name?: string | null;
  readonly group_contact_email?: string | null;
  readonly group_contact_phone?: string | null;
  readonly user_email?: string | null;
  readonly user_role?: string | null;
  readonly createdAt?: string | null;
  readonly sortkey?: string | null;
  constructor(init: ModelInit<Usergroup>);
  static copyOf(source: Usergroup, mutator: (draft: MutableModel<Usergroup>) => MutableModel<Usergroup> | void): Usergroup;
}

export declare class Insurance {
  readonly id: string;
  readonly groupId?: string | null;
  readonly userId?: string | null;
  readonly investorId?: string | null;
  readonly supplierId?: string | null;
  readonly brokerId?: string | null;
  readonly spvId?: string | null;
  readonly buyerId?: string | null;
  readonly insuranceId: string;
  readonly identityId?: string | null;
  readonly insurance_type?: string | null;
  readonly insurance_name?: string | null;
  readonly insurance_supplier_uuid?: string | null;
  readonly insurance_supplier_duns?: string | null;
  readonly insurance_buyer_uuid?: string | null;
  readonly insurance_buyer_duns?: string | null;
  readonly insurance_cover_amount?: string | null;
  readonly insurance_cover_currency?: string | null;
  readonly insurance_cover_start_date?: string | null;
  readonly insurance_cover_end_date?: string | null;
  readonly insurance_cover_status?: string | null;
  readonly insurance_cover_type?: string | null;
  readonly insurance_cover_premium?: string | null;
  readonly insurance_cover_premium_currency?: string | null;
  readonly insurance_cover_collateral_currency?: string | null;
  readonly insurance_cover_exchange_rate?: string | null;
  readonly insurance_single_invoice_cover_amount?: string | null;
  readonly insurance_single_invoice_cover_currency?: string | null;
  readonly insurance_single_invoice_cover_start_date?: string | null;
  readonly insurance_single_invoice_cover_end_date?: string | null;
  readonly insurance_single_invoice_cover_status?: string | null;
  readonly insurance_single_invoice_cover_premium?: string | null;
  readonly insurance_single_invoice_cover_premium_currency?: string | null;
  readonly insurance_single_invoice_cover_collateral_currency?: string | null;
  readonly insurance_single_invoice_exchange_rate?: string | null;
  readonly group_contact_name?: string | null;
  readonly group_contact_email?: string | null;
  readonly group_contact_phone?: string | null;
  readonly user_email?: string | null;
  readonly user_role?: string | null;
  readonly createdAt?: string | null;
  readonly sortkey?: string | null;
  constructor(init: ModelInit<Insurance>);
  static copyOf(source: Insurance, mutator: (draft: MutableModel<Insurance>) => MutableModel<Insurance> | void): Insurance;
}