/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateCompany = /* GraphQL */ `
  subscription OnCreateCompany($sortkey: String, $userId: String) {
    onCreateCompany(sortkey: $sortkey, userId: $userId) {
      companyId
      company_address_city
      company_address_number
      company_address_postalcode
      company_address_refinment
      company_country
      company_director_appointment_date
      company_director_country_of_residence
      company_director_date_of_birth
      company_director_email
      company_director_id_attachment
      company_director_id_expiry_date
      company_director_id_issue_date
      company_director_id_issuer_country
      company_director_id_issuer_state
      company_director_id_number
      company_director_id_type
      company_director_jobtitle
      company_director_name
      company_director_nationality
      company_director_pep_status
      company_director_phone_number
      company_director_poa_attachment
      company_director_ubo_status
      company_industry
      company_industry_code
      company_name
      company_register_number
      company_trading_name
      company_type
      company_ubo_appointment_date
      company_ubo_country_of_residence
      company_ubo_date_of_birth
      company_ubo_email
      company_ubo_id_attachment
      company_ubo_id_expiry_date
      company_ubo_id_issue_date
      company_ubo_id_issuer_country
      company_ubo_id_issuer_state
      company_ubo_id_number
      company_ubo_id_type
      company_ubo_jobtitle
      company_ubo_name
      company_ubo_nationality
      company_ubo_ownership_percentage
      company_ubo_pep_status
      company_ubo_phone_number
      company_ubo_poa_attachment
      company_website
      companyaddress_street
      createdAt
      date_of_incorporation
      registration_cert_attachment
      sortkey
      userId
    }
  }
`;
export const onCreateCompanyBank = /* GraphQL */ `
  subscription OnCreateCompanyBank($sortkey: String, $userId: String) {
    onCreateCompanyBank(sortkey: $sortkey, userId: $userId) {
      account_statement_attachment
      balance
      balance_available
      bank_account_name
      bank_account_number
      bank_account_sortcode
      bank_address_city
      bank_address_number
      bank_address_postalcode
      bank_address_refinment
      bank_address_street
      bank_branch
      bank_country
      bank_name
      bank_routing_number
      bic_swift_code
      createdAt
      iban
      iso_currency_code
      overdraft
      payments_incoming
      payments_outgoing
      pre_auth_amount
      reporting_end_date
      reporting_start_date
      sortkey
      userId
    }
  }
`;
export const onCreateCompanyFinancials = /* GraphQL */ `
  subscription OnCreateCompanyFinancials($sortkey: String, $userId: String) {
    onCreateCompanyFinancials(sortkey: $sortkey, userId: $userId) {
      accounts_payable
      accounts_receivable
      cash
      createdAt
      ebit
      equity_book_value
      equity_market_value
      financial_accounts_attachment
      financialsId
      interest_expenses
      inventory
      net_profit
      reporting_period
      retained_earnings
      sales
      short_term_debt
      sortkey
      total_assets
      total_liabilities
      userId
      working_capital
    }
  }
`;
export const onCreateProject = /* GraphQL */ `
  subscription OnCreateProject($sortkey: String, $userId: String) {
    onCreateProject(sortkey: $sortkey, userId: $userId) {
      buyerId
      buyer_address_city
      buyer_address_number
      buyer_address_postalcode
      buyer_address_refinment
      buyer_address_street
      buyer_company_name
      buyer_country
      buyer_rating
      createdAt
      currency
      insurance_name
      insurance_rating
      insurance_status
      loan_amount
      loan_attachment
      loan_collateral
      loan_covenants
      loan_fees
      loan_purpose
      loan_rate
      loan_type
      next_year_projected_transaction_amount
      payment_terms
      previous_year_transaction_amount
      projectId
      purchase_order_amount
      purchase_order_attachment
      purchase_order_date
      reporting_year
      reporting_year_transaction_amount
      sales_contract_attachment
      sold_goods_description
      sortkey
      title
      userId
    }
  }
`;
export const onDeleteCompany = /* GraphQL */ `
  subscription OnDeleteCompany($sortkey: String, $userId: String) {
    onDeleteCompany(sortkey: $sortkey, userId: $userId) {
      companyId
      company_address_city
      company_address_number
      company_address_postalcode
      company_address_refinment
      company_country
      company_director_appointment_date
      company_director_country_of_residence
      company_director_date_of_birth
      company_director_email
      company_director_id_attachment
      company_director_id_expiry_date
      company_director_id_issue_date
      company_director_id_issuer_country
      company_director_id_issuer_state
      company_director_id_number
      company_director_id_type
      company_director_jobtitle
      company_director_name
      company_director_nationality
      company_director_pep_status
      company_director_phone_number
      company_director_poa_attachment
      company_director_ubo_status
      company_industry
      company_industry_code
      company_name
      company_register_number
      company_trading_name
      company_type
      company_ubo_appointment_date
      company_ubo_country_of_residence
      company_ubo_date_of_birth
      company_ubo_email
      company_ubo_id_attachment
      company_ubo_id_expiry_date
      company_ubo_id_issue_date
      company_ubo_id_issuer_country
      company_ubo_id_issuer_state
      company_ubo_id_number
      company_ubo_id_type
      company_ubo_jobtitle
      company_ubo_name
      company_ubo_nationality
      company_ubo_ownership_percentage
      company_ubo_pep_status
      company_ubo_phone_number
      company_ubo_poa_attachment
      company_website
      companyaddress_street
      createdAt
      date_of_incorporation
      registration_cert_attachment
      sortkey
      userId
    }
  }
`;
export const onDeleteCompanyBank = /* GraphQL */ `
  subscription OnDeleteCompanyBank($sortkey: String, $userId: String) {
    onDeleteCompanyBank(sortkey: $sortkey, userId: $userId) {
      account_statement_attachment
      balance
      balance_available
      bank_account_name
      bank_account_number
      bank_account_sortcode
      bank_address_city
      bank_address_number
      bank_address_postalcode
      bank_address_refinment
      bank_address_street
      bank_branch
      bank_country
      bank_name
      bank_routing_number
      bic_swift_code
      createdAt
      iban
      iso_currency_code
      overdraft
      payments_incoming
      payments_outgoing
      pre_auth_amount
      reporting_end_date
      reporting_start_date
      sortkey
      userId
    }
  }
`;
export const onDeleteCompanyFinancials = /* GraphQL */ `
  subscription OnDeleteCompanyFinancials($sortkey: String, $userId: String) {
    onDeleteCompanyFinancials(sortkey: $sortkey, userId: $userId) {
      accounts_payable
      accounts_receivable
      cash
      createdAt
      ebit
      equity_book_value
      equity_market_value
      financial_accounts_attachment
      financialsId
      interest_expenses
      inventory
      net_profit
      reporting_period
      retained_earnings
      sales
      short_term_debt
      sortkey
      total_assets
      total_liabilities
      userId
      working_capital
    }
  }
`;
export const onDeleteProject = /* GraphQL */ `
  subscription OnDeleteProject($sortkey: String, $userId: String) {
    onDeleteProject(sortkey: $sortkey, userId: $userId) {
      buyerId
      buyer_address_city
      buyer_address_number
      buyer_address_postalcode
      buyer_address_refinment
      buyer_address_street
      buyer_company_name
      buyer_country
      buyer_rating
      createdAt
      currency
      insurance_name
      insurance_rating
      insurance_status
      loan_amount
      loan_attachment
      loan_collateral
      loan_covenants
      loan_fees
      loan_purpose
      loan_rate
      loan_type
      next_year_projected_transaction_amount
      payment_terms
      previous_year_transaction_amount
      projectId
      purchase_order_amount
      purchase_order_attachment
      purchase_order_date
      reporting_year
      reporting_year_transaction_amount
      sales_contract_attachment
      sold_goods_description
      sortkey
      title
      userId
    }
  }
`;
export const onUpdateCompany = /* GraphQL */ `
  subscription OnUpdateCompany($sortkey: String, $userId: String) {
    onUpdateCompany(sortkey: $sortkey, userId: $userId) {
      companyId
      company_address_city
      company_address_number
      company_address_postalcode
      company_address_refinment
      company_country
      company_director_appointment_date
      company_director_country_of_residence
      company_director_date_of_birth
      company_director_email
      company_director_id_attachment
      company_director_id_expiry_date
      company_director_id_issue_date
      company_director_id_issuer_country
      company_director_id_issuer_state
      company_director_id_number
      company_director_id_type
      company_director_jobtitle
      company_director_name
      company_director_nationality
      company_director_pep_status
      company_director_phone_number
      company_director_poa_attachment
      company_director_ubo_status
      company_industry
      company_industry_code
      company_name
      company_register_number
      company_trading_name
      company_type
      company_ubo_appointment_date
      company_ubo_country_of_residence
      company_ubo_date_of_birth
      company_ubo_email
      company_ubo_id_attachment
      company_ubo_id_expiry_date
      company_ubo_id_issue_date
      company_ubo_id_issuer_country
      company_ubo_id_issuer_state
      company_ubo_id_number
      company_ubo_id_type
      company_ubo_jobtitle
      company_ubo_name
      company_ubo_nationality
      company_ubo_ownership_percentage
      company_ubo_pep_status
      company_ubo_phone_number
      company_ubo_poa_attachment
      company_website
      companyaddress_street
      createdAt
      date_of_incorporation
      registration_cert_attachment
      sortkey
      userId
    }
  }
`;
export const onUpdateCompanyBank = /* GraphQL */ `
  subscription OnUpdateCompanyBank($sortkey: String, $userId: String) {
    onUpdateCompanyBank(sortkey: $sortkey, userId: $userId) {
      account_statement_attachment
      balance
      balance_available
      bank_account_name
      bank_account_number
      bank_account_sortcode
      bank_address_city
      bank_address_number
      bank_address_postalcode
      bank_address_refinment
      bank_address_street
      bank_branch
      bank_country
      bank_name
      bank_routing_number
      bic_swift_code
      createdAt
      iban
      iso_currency_code
      overdraft
      payments_incoming
      payments_outgoing
      pre_auth_amount
      reporting_end_date
      reporting_start_date
      sortkey
      userId
    }
  }
`;
export const onUpdateCompanyFinancials = /* GraphQL */ `
  subscription OnUpdateCompanyFinancials($sortkey: String, $userId: String) {
    onUpdateCompanyFinancials(sortkey: $sortkey, userId: $userId) {
      accounts_payable
      accounts_receivable
      cash
      createdAt
      ebit
      equity_book_value
      equity_market_value
      financial_accounts_attachment
      financialsId
      interest_expenses
      inventory
      net_profit
      reporting_period
      retained_earnings
      sales
      short_term_debt
      sortkey
      total_assets
      total_liabilities
      userId
      working_capital
    }
  }
`;
export const onUpdateProject = /* GraphQL */ `
  subscription OnUpdateProject($sortkey: String, $userId: String) {
    onUpdateProject(sortkey: $sortkey, userId: $userId) {
      buyerId
      buyer_address_city
      buyer_address_number
      buyer_address_postalcode
      buyer_address_refinment
      buyer_address_street
      buyer_company_name
      buyer_country
      buyer_rating
      createdAt
      currency
      insurance_name
      insurance_rating
      insurance_status
      loan_amount
      loan_attachment
      loan_collateral
      loan_covenants
      loan_fees
      loan_purpose
      loan_rate
      loan_type
      next_year_projected_transaction_amount
      payment_terms
      previous_year_transaction_amount
      projectId
      purchase_order_amount
      purchase_order_attachment
      purchase_order_date
      reporting_year
      reporting_year_transaction_amount
      sales_contract_attachment
      sold_goods_description
      sortkey
      title
      userId
    }
  }
`;
export const onCreateOriginate = /* GraphQL */ `
  subscription OnCreateOriginate($sortkey: String, $userId: String) {
    onCreateOriginate(sortkey: $sortkey, userId: $userId) {
      sortkey
      userId
    }
  }
`;
export const onUpdateOriginate = /* GraphQL */ `
  subscription OnUpdateOriginate($sortkey: String, $userId: String) {
    onUpdateOriginate(sortkey: $sortkey, userId: $userId) {
      sortkey
      userId
    }
  }
`;
export const onDeleteOriginate = /* GraphQL */ `
  subscription OnDeleteOriginate($sortkey: String, $userId: String) {
    onDeleteOriginate(sortkey: $sortkey, userId: $userId) {
      sortkey
      userId
    }
  }
`;
