import NewBrokerFormModel from "./NewBrokerFormModel";
const {
  formField: {
    broker_logo,
    broker_name,
    broker_type,
    broker_date_of_incorporation,
    broker_address_city,
    broker_address_street,
    broker_address_postalcode,
    broker_country,
    broker_industry,
    broker_registration_cert_attachment,
    broker_articles_of_association_attachment,
    broker_shareholder_list_attachment,
    broker_director_list_attachment,
    broker_register_number,
    broker_trading_name,
    broker_website,
    broker_address_refinment,
    broker_industry_code,
    director_name,
    director_email,
    director_phone_number,
    director_id_attachment,
    director_id_number,
    director_id_type,
    director_nationality,
    director_poa_attachment,
    director_country_of_residence,
    ubo_name,
    ubo_email,
    ubo_phone_number,
    ubo_id_attachment,
    ubo_id_number,
    ubo_id_type,
    ubo_nationality,
    ubo_poa_attachment,
    ubo_country_of_residence,
    buyerId,
    accounts_payable,
    accounts_receivable,
    cash,
    equity_book_value,
    equity_market_value,
    interest_expenses,
    inventory,
    retained_earnings,
    short_term_debt,
    working_capital,
    ebit,
    financials_attachment,
    net_profit,
    financials_rating,
    financials_reporting_period,
    sales,
    total_assets,
    total_liabilities,
  },
} = NewBrokerFormModel;

const values = {
  [broker_logo.name]: "",
  [broker_name.name]: "",
  [broker_trading_name.name]: "",
  [broker_website.name]: "",
  [broker_type.name]: "",
  [broker_date_of_incorporation.name]: "",
  [broker_address_city.name]: "",
  [broker_address_street.name]: "",
  [broker_address_postalcode.name]: "",
  [broker_address_refinment.name]: "",
  [broker_country.name]: undefined,
  [broker_industry.name]: undefined,
  [broker_industry_code.name]: undefined,
  [broker_register_number.name]: "",
  [broker_registration_cert_attachment.name]: "",
  [broker_articles_of_association_attachment.name]: "",
  [broker_shareholder_list_attachment.name]: "",
  [broker_director_list_attachment.name]: "",
  [director_name.name]: "",
  [director_email.name]: "",
  [director_phone_number.name]: "",
  [director_id_attachment.name]: "",
  [director_id_number.name]: "",
  [director_id_type.name]: "",
  [director_nationality.name]: undefined,
  [director_poa_attachment.name]: "",
  [director_country_of_residence.name]: undefined,
  [ubo_name.name]: "",
  [ubo_email.name]: "",
  [ubo_phone_number.name]: "",
  [ubo_id_attachment.name]: "",
  [ubo_id_number.name]: "",
  [ubo_id_type.name]: "",
  [ubo_nationality.name]: undefined,
  [ubo_poa_attachment.name]: "",
  [ubo_country_of_residence.name]: undefined,
  [ebit.name]: "",
  [financials_attachment.name]: "",
  [buyerId.name]: "",
  [net_profit.name]: "",
  [financials_rating.name]: "",
  [financials_reporting_period.name]: "",
  [sales.name]: "",
  [total_assets.name]: "",
  [total_liabilities.name]: "",
  [accounts_payable.name]: "",
  [accounts_receivable.name]: "",
  [cash.name]: "",
  [equity_book_value.name]: "",
  [equity_market_value.name]: "",
  [interest_expenses.name]: "",
  [inventory.name]: "",
  [retained_earnings.name]: "",
  [short_term_debt.name]: "",
  [working_capital.name]: "",
};

export default values;
